mylar3/mylar3

mylar/webviewer.py
=> FIX: CherryPy changes (again) - 15.0 this time

mylar/webviewer.py
=> FIX: no need to decode as unicode in py3

mylar/webserve.py
=> FIX: StringIO doesn't work with bytestreams in py3

mylar/librarysync.py, mylar/webserve.py
=> FIX: Import type errors

mylar/updater.py
=> FIX: crash when exceptions table missing

mylar/notifiers.py, mylar/versioncheck.py
Without this fix, the git version check fails on Windows
=> [FIX] platform independent devnull location + bug in sending covers to Telegram

mylar/cv.py, mylar/webserve.py
updated issuedetails to check if Issue Name and Issue Number is present before attempting to display the items
=> fixed traceback error when displaying issue with no issue name.

mylar/carepackage.py
goddamnit who cares its all whitespace
=> FIX: TabError: inconsistent use of tabs and spaces in indentation

mylar/__init__.py, mylar/encrypted.py, mylar/search.py
- fixed search results error
- removed encryption logging
- changed sql initialization to allow for module calls
=> fix search results error, sql initialization change, removed encryption logging

data/interfaces/default/config.html
=> FIX: incorrect variable name

mylar/config.py
per @ajslater, evilhero/mylar #2425
=> FIX: import referenced library

mylar/getimage.py, mylar/helpers.py, mylar/webserve.py
- increased numerical comparison in order to retrieve proper image within archive
- update tuple to return proper information
- update display in GUI to show updated information
=> various cover image display fixes

data/interfaces/default/base.html, data/interfaces/default/manage.html
Fix calling turnitoff() before its declared.
Same as the patch from mylar2
=> fix turnitoff error

mylar/librarysync.py
Import dies on a key error trying to access issueinfo[0].
accessing issueinfo['metadata'] fixes it.
=> fix import to use metadata key

mylar/torrent/clients/qbittorrent.py
Additional error logging when trying to add a torrent using qbittorrent.
=> Qbittorrent logging

data/interfaces/default/config.html, mylar/config.py, mylar/helpers.py, mylar/search.py, mylar/webserve.py
torznab test implementation for mylar3
torznab test was only partially implemented on the front end and never implemented on the back end, which of course made the test button fail as noticed in #2035
The partial front end torznab test implementation did not expose a Verify SSL button, but this PR does implement one on the front and back end.
=> implement torznab tester

mylar/carepackage.py
A couple of instances of PROG_DIR shoulda been DATA_DIR and now mylar3 generates carepackages.
=> Fix carepackage generation

Mylar.py, mylar/versioncheck.py
- (#126) make sure reference to .LAST_RELEASE looks in full data_path
-Changed variable reference from file to open when in daemon mode
=> some startup fixes

mylar/webserve.py
=> Revert "Fix restart queue empty"

Mylar.py
=> Revert "pidfile tweaks"

Mylar.py
1. Make pidfile actually use the PPID rather than the word "pid"
2. Add stale pid file detection which works like:
- Is paltform linux w/proc?  No?  It's not stale
- Read the pid from pidfile.  Does it exist on this system?  No?  It's stale
- Read if /proc/{pid}/cmdline, converting '\0' to spaces.  If python in the cmdline?  If no, then it's stale.  Otherwise we assume it's not.
=> pidfile normalcy

Dockerfile
Alpine 3.11 based Dockerfile for mylar3
replaces #121
=> Dockerfile for mylar3

data/interfaces/default/manage.html, mylar/webserve.py
- FIX:(#155) Scan Comic Library settings were not persistent. 
- Corrected incorrect variable reference in newzanb test & torznab test options for non-ssl providers
=> Comic Library settings persistent

README.md
=> Revert "FIX: Windows pip requirements"

mylar/rsscheckit.py
=> FIX?: try/except around 32p rss feedinfo

mylar/rsscheckit.py
Reverts mylar3/mylar3#192 - wrong branch
=> Revert "FIX?: try/except around 32p rss feedinfo"

mylar/rsscheckit.py
=> FIX: try/except around feedinfo

mylar/cv.py
=> FIX: avoid error when CV data incomplete

data/interfaces/default/base.html, data/interfaces/default/css/style.css, data/interfaces/default/history.html, data/interfaces/default/storyarc.html, mylar/webserve.py
- Improved loading time in history page by only loading viewing page instead of entire dataset. 
- Moved Logs option from Top NavBar to History tab as an button option. 
- Replaced Logs option from NavBar with StoryArcs.
=> History template updates

README.md
=> Added missing steps to migration instructions

.gitignore, mylar/getcomics.py
=> FIX: better handling of gc unreachability

data/interfaces/default/css/style.css, data/interfaces/default/index.html, mylar/helpers.py, mylar/webserve.py
- Volume included in display if present within series info
- filterbox works with new template
=> home improvements

mylar/PostProcessor.py
fix for post-processing TPB's during a manual run if the TPB had an issue number with a decimal place
=> FIX: manual post-processing run of TPB with decimal issue

mylar/helpers.py, mylar/importer.py
=> FIX: Ampersands in issuenums

mylar/helpers.py, mylar/importer.py
Small required base-work for upcoming future improvements:
- Removes all attempts to encode the Issue Name (Partially fixes #282 - db conversion is still required to be completed)
- Better check of comlocation being set prior to attempting to create a series directory during a series add / refresh.
=> small base-work update for future improvements

mylar/db.py, mylar/filers.py, mylar/mb.py, mylar/webserve.py
- Fixed incorrect DB SQL error trapping errors.
- If $Type was being used, when recreating directory would default to None instead of Print
- Added some fallback to CV image retrieval based on image size
- NZBGet removal of information from logs
- Removed unquoting of DB data from issue details popup
=> small patches

data/interfaces/carbon/comicdetails.html, data/interfaces/default/comicdetails.html
=> FIX: aissuename = none

mylar/opds.py
Fixes #327 - thanks @micket for the sample code!
=> FIX: some IssueDetails calls expected list responses instead of dicts

data/interfaces/carbon/comicdetails.html
Fight branch this time. Case sensitivity is still BAD
=> FIX: #329 carbon-flavored

data/interfaces/carbon/css/data_table.css, data/interfaces/carbon/css/style.css
1. Centered the table values and checkboxes across the interface
2. Change the hover link colour.
Screenshots:
=> centered tables and change hover link color

mylar/opds.py
IMP: Add logging for OPDS & readinglist interaction (to assist with #357)
=> IMP: Add logging for OPDS & readinglist interaction

mylar/search.py
=> FIX: remove unused nzbget_param variable

data/interfaces/default/opds.html, mylar/getimage.py, mylar/opds.py
Some bad news; trying to get this to work with android clients, i found out that
1. Kuboo hardcodes a whole bunch of ubooquity specific urls instead or using the links that the OPDS requests gives it. I can't get it to work. 
2. Challenger Viewer also adds a bunch of nondocumented variables to the url. Even trying to accomodate those, I couldn't get it to work.
So, neither of them follows the spec at all. :-1: 
Everything looks right in my manual inspections though.
=> Mostly working streaming OPDS implementation

mylar/opds.py
And learn to read, while I'm at it
Fixes #357 for good this time
=> FIX: pass IssueID to markasRead the right way

mylar/readinglist.py
=> IMP: Logging when markasRead doesnt get input

mylar/opds.py
=> FIX: point issue['fileloc'] to the right place in OPDS

mylar/rsscheck.py, mylar/search.py
Also updated the searchforissueidlist module in search.py to use the corrected_booktype if it's set to something other than None.
=> FIX:(#381) Change dog RSS to use API cause the RSS doesn't work

data/interfaces/carbon/css/style.css
=> FIX: Hover is lost against a silver background

mylar/weeklypull.py
=> FIX: YAUtfEncode

mylar/PostProcessor.py
Clean patch from #416 - thanks @kalinon !
=> catches error raised by post processing

mylar/filechecker.py, mylar/rsscheck.py
=> Revert "python3-dev merge"

mylar/PostProcessor.py, mylar/search.py
- FIX: fix for DDL not searching for one-shot issues properly (especially one-off's via the pullist), 
- FIX: fix for one-off post-processing error
=> FIX: DDL searching & post-processing would fail if one-off from weekly pull

mylar/filechecker.py, mylar/helpers.py, mylar/importer.py
Thought we fixed this at some point over the last year(s) - not sure what happened, but putting it back.
=> FIX:(#480) Allow for Omega and Alpha numbering

mylar/carepackage.py, mylar/config.py
- Fixed a small carepackage problem for new installations not being able to find unset variables
=> FIX:(#520) Fixed startup logger problems on non-English systems

data/interfaces/default/logs.html, data/interfaces/default/opds.html, mylar/getcomics.py, mylar/search.py, mylar/webserve.py
- FIX:(#538) RSS cache would not be referenced properly against newznab providers tagged as [localhost] or [nzbhydra]
- FIX: fix for DDL throwing challenge errors and killing the queue, 
- FIX: searches doing an extra loop for non-loopable providers (ie. DDL, experimental), 
- FIX: removed timeout after search for non-loopable providers
- FIX: fixed traceback GUI dialog so that it can delete specific entries
- FIX: ugly monkeypatch to exception GUI display so screen doesn't have to be refreshed
- IMP: black + flake8 done to getcomics.py
- FIX: mako error in opds.html (@cnewham699)
=> Python3 dev

mylar/search.py
Problem seem to be occurring when the publication date is prior to 1970 AND on a different timezone?
=> FIX:(#538) Attempt to fix some mktime conversion

data/interfaces/default/read.html
Avoid attempts to load next/previous page if there is no next/previous page.
=> Added next/previous page check

data/interfaces/default/logs.html, data/interfaces/default/opds.html, data/interfaces/default/read.html, mylar/api.py, mylar/filechecker.py, mylar/getcomics.py, mylar/opds.py, mylar/search.py, mylar/webserve.py, mylar/webviewer.py
- FIX: (#548) Properly detecting variations of unicode dashes and represent them as a single dash when comparing/matching/etc
- IMP:(#257) api method changeStatus added to allow for mass changing of status' by comicid
- FIX: (#538) Attempt to fix some mktime conversion problems that are occurring when the publication date is prior to 1970 AND on a different timezone?
- FIX:(#553) incorrect variable used to reference file location
- FIX: Pull-list may show every issue on the pull as Snatched instead of Skipped
- IMP: recheckFiles api method added to allow for batch rechecking of series based on comicid
- OPDS: Added next/previous page check, and encoding filenames for web-viewer (@nymitr)
=> Python3-dev merge

mylar/sabnzbd.py
If SABnzbd was in the middle of a status update (ie. Queuing, Waiting, w/e) and Mylar was attempting to check the history, would find the nzo_id but with an invalid status and wouldn't retry so the send to the post-processor wouldn't initiate
=> FIX: CDH failing to find nzo_id in SABnzbd if status was Queued (timing-related)

mylar/helpers.py, mylar/locg.py
- FIX: fixed pull-list attempting to poll week 0, 2020 instead of week 52, 2020 or week 1, 2021 (resulted in empty pull-list)
- FIX: pull_refresh value in ini will now be written out after each pull refresh (it stores it in the db, but w/e)
=> Pull-list patch for year flipping to 2021

post-processing/autoProcessComics.py
FIX: #498 Py3 migration issue re bytes and NZBGet - with autoProcessComics
=> FIX: #498 Py3 migration issue re bytes and NZBGet

post-processing/autoProcessComics.py
=> Revert "Python3 dev"

mylar/webserve.py
=> Revert "Update webserve.py"

mylar/webviewer.py
Some cbr/cbz contain actual files in subfolder.
=> Made webviewer use correct relative path

mylar/updater.py
Kinda niche, but...
During  a ReCheck Files, when dealing with issues that do not exist in a Downloaded status, Mylar compares each issue in the db for a given comic to see if it's in a previously Downloaded status or not in order to check to see if it should be changed to Archived. 
It compared the entire issue set previously - this PR limits it to just issues that have not already been physically found within the given series directory, which will speed up the ReCheck overall since it's not doing the same thing more than once.
=> IMP: Speed up checking for non-existent issues during a ReCheck Files

requirements.txt
FIX: add pystun to requirements (fixes #656) - thank you @lcmsilek!
=> FIX: add pystun to requirements (fixes #656)

requirements.txt
https://pypi.org/project/pystun/#history
=> fix pystun version in requirements.txt

mylar/updater.py
- IMP: DBUpdater will not start if it was started within last 15 minutes (to avoid constant checks when restarting several times) ,as opposed to running on every start regardless.
-FIX: Fixed Updater status would not change the status from Running to Waiting when completed run.
=> IMP: DBUpdater will not start if it was started within last 15 minutes; DB Updater status fixed

data/interfaces/default/storyarc.html, mylar/config.py, mylar/helpers.py, mylar/webserve.py
Supercedes Pull Request #697
(thanks @davalanche!)
=> IMP:(#652) StoryArcs: Added the option to make symlinks relative

data/interfaces/default/weeklypull.html, data/js/libs/circular-json.js, data/js/libs/selectize.js, data/js/script.js, mylar/config.py, mylar/importer.py, mylar/webserve.py, mylar/weeklypull.py
IMP: Added ability to select based on publisher name for mass add it all option of weeklypull via popup dialog.
IMP: Mass add.it.all option can now be set to run on every pull refresh and/or run manually.
IMP: Updated some button icons that were identical
=> IMP: mass add.it.all option select based on publisher name

mylar/api.py
repushed new branch with api fixes.
=> fixed two api calls that were broken

mylar/helpers.py, mylar/importer.py
… raised with #715.
i have put in an algorithm to generate consistant issue numbers from issue spreads based on what was there.
There is still an issue where the issue number generation code is duplicated between both the import code and the helper code.
=> Importing multi-issue Issues.

data/interfaces/default/history.html, data/interfaces/default/searchresults.html, data/interfaces/default/storyarc.html, mylar/webserve.py
Removed unused 'type = 'comic' from import function
Renamed type to search_type in searchit()
Renamed type to status_type in clearhistory()
Having variables with the same name as the builtin function caused errors on import. Made suggested fix by renaming variables.
=> Fixed shadowing of builtin function type()

data/interfaces/default/searchresults.html, mylar/api.py, mylar/helpers.py, mylar/mb.py, mylar/webserve.py
- FIX: fix for storyarc searches being broken
- FIX: corrected some incorrect variable references due to a previous PR
=> FIX: broken story arc searches, FIX: incorrect variable references

README.md
- Updated readme.md so that only bullet points are on the readme linking to related wiki posts.
- Tried to keep it as 'clean' as possible, and used sonarr's readme as the basis for the changeup ( much <3 to the guys )
=> Updated readme.md to work with wiki linking

mylar/webserve.py
FIX: fix for series folder not existing when trying to create series.json file
FIX: if Comic Location wasn't created prior to opening up the series detail page, would temporarily throw a 500
=> small series.json fixes

mylar/PostProcessor.py
When attempting to manually post-process issues that don't have any CV data yet, but may match to other series on the watchlist - Mylar would incorrectly assumes matches in some cases based on name-matching incorrectly.  This seemed to occur when Mylar thought variations of the series name in the filename existed (ie. they contained a hyphen or similar), and those variations matched up to a series currently on a user's watchlist.
Will now verify against the pull-list for any matching incomplete series details (name & issue number) as well as using the latest date of the particular series prior to accepting as a valid match for post-processing.
=> FIX: Issues with no CV data would sometimes incorrectly match to watchlist series based on name & basic issue number matching

data/interfaces/carbon/css/style.css, data/interfaces/default/comicdetails.html
- FIX: (carbon theme) fix for series detail page issue columns having overlap and improper lengths
- IMP: Added a graphic symbol to the directory location on the series detail page to indicate whether the location exists or not
=> FIX: incorrect issue columns length on series detail page, IMP: display if series directory is present or not on series detail page

data/css/style.css, data/interfaces/carbon/css/style.css, data/interfaces/default/css/style.css
- FIX: default theme had incorrect issue & annual table css for series detail pages, 
- FIX: carbon theme fixed annuals table so it's identical to issues table
- FIX: default theme index css columns
=> FIX: fix incorrect css across both themes regarding series detail page & index page

mylar/PostProcessor.py
- FIX: issues for series that are 100% completed, but marked as Wanted/Snatched not being post-processed
- FIX: ignore_covers option now honoured when post-processing
=> FIX: post-processing related issues (100% completion, ignore_covers)

data/interfaces/default/comicdetails.html, mylar/PostProcessor.py
- FIX: Fix for non-displaying checkmark/x-icon on series detail page for Comic Location
- FIX: post-processing of TPB that were recently released would get rejected even if valid
=> FIX: (#821) post-processing recent TBP issues; display icon for Comic Location path on series detail page

mylar/Failed.py, mylar/helpers.py, mylar/nzbget.py, mylar/process.py, mylar/sabnzbd.py, mylar/search.py
- also changed nzbget output so it wouldn't display full host details when logging.
=> FIX: addressed some problems with failed downloading handling with CDH & nzb providers

mylar/cv.py
- The DBUpdater was using the incorrect sequnce of dates, which would mean that the start range would be later than the end range, which would resutl in no results when the db updater would run (which would affect any recent updates outside of the pull - and even the pull to a degree).
- Changed outlying call that dbUpdate uses to submit date-range queries based on PST time (UTC-7), and not UTC. 
This will convert existing UTC timestamps stored in the database, to localised tz-based timestamp, then convert that to PST and submit the PST data to CV. The datestamp that is used in the query and returned from CV only affects the ``date_last_updated`` field that I've noticed, so it really shouldn't affect.
=> FIX: DBupdate using incorrect date sequences, FIX: CV API returns API date times as PST timezone (not TZ aware)

data/interfaces/default/base.html
=> FIX: logout option would appear even if no authentication was being used

mylar/cv.py, mylar/filechecker.py, mylar/webserve.py
- FIX: files starting with a decimal, for series beginning with a decimal would not be detected
- FIX: publisher imprint error could fail to update settings on save
- FIX: if CV has series as 'digital graphic novel', try to ensure it detects as a 'graphic novel'
=> FIX: series starting with decimals would not be able to detect files starting with decimals, FIX: publisher imprint save error

data/interfaces/default/logs.html, mylar/webserve.py
- IMP: changed Toggle Verbose button to (Enable / Disable) Debug Logging depending on logging level enabled.
- IMP: Added ``Clear All Specific Logs`` to Exceptions/Tracebacks option
=> IMP: Toggle Verbose button changed to Enable/Disable Debug Logging, IMP: Clear All Specific Logs option added

mylar/cv.py, mylar/importer.py
- FIX: one-shots not being detected properly until after directory creation creating incorrect directory locations initially
- FIX month value check for imprint matching was incorrectly being calculated
=> FIX: one-shots not being detected properly until after directory creation, FIX month value check for imprint matching was incorrect

data/interfaces/default/base.html, mylar/__init__.py, mylar/api.py, mylar/webserve.py
- FIX: Randomized sse_key at runtime, instead of constant
- FIX: Enforce sse_key being only allowable for internal messaging
- FIX: Increased popup for add series from 3s to 5s
=> sse key updates

data/interfaces/default/index.html, mylar/PostProcessor.py, mylar/__init__.py, mylar/helpers.py, mylar/importer.py, mylar/sabnzbd.py
- FIX: Allow for .BEY issue numbering across various modules
- FIX: Allow for extra numbering in latest issue column on index page
- FIX: properly trap sabnzbd when it can't pop the search term
- FIX: delete NULL publishers from weekly table on startup as it can cause errors when viewing the weekly pull
=> FIX: allow for .BEY issue numbering

lib/certgen.py
Fixed up createCertificate parameters as per PEP 3113
=> Update certgen.py per PEP 3113 (tuple parameters)

data/interfaces/carbon/css/style.css, data/interfaces/default/base.html, data/interfaces/default/css/style.css
=> FIX: glow on mylar logo, IMP: cachebuster for style.css (thnx @btxgit)

mylar/config.py
would fail to startup due to error because of ini and db being updated.
=> FIX: startup error due to invalid call

Mylar.py, mylar/__init__.py, mylar/config.py, mylar/maintenance.py
=> FIX: recent config.ini related errors due to last PR, FIX: db updater was not firing

mylar/notifiers.py
Added an embed to the discord notifications to make them quicker to parse visually.
=> Make Discord notification prettier

mylar/notifiers.py
=> Change Discord timestamp to UTC

mylar/PostProcessor.py, mylar/notifiers.py
Added embedded cover image to Discord post-processed notification.
=> Added images in discord embed

mylar/__init__.py, mylar/helpers.py, mylar/weeklypull.py
- FIX: weekly pull would not update some series due to traceback error re: statusupdate
- FIX: show scheduler run times when logging as localised, not UTC
=> FIX: weeklypull would not update some series due to traceback error, FIX: Scheduler run times localised logging

mylar/cmtagmylar.py, mylar/getcomics.py, mylar/search.py, mylar/search_filer.py
- FIX: list index error when searching with GC
- IMP: remove unneeded logging lines during search
- IMP: add extra logging to tagging for better error capturing
- FIX: cookies not being read with GC even tho being saved (delete & recreate now)
=> small GC fixes and increased logging during cbr-cbz conversion

mylar/maintenance.py
- FIX: Maintenance Updater would die on trying to parse invalid filenames
- IMP: Added deletion of invalid rss entries and vacuum after maintenance completion
=> FIX: Maintenance Updater would die when encountering invalid filenames 

mylar/PostProcessor.py, mylar/findcomicfeed.py, mylar/rsscheck.py, mylar/search.py, mylar/torrent/clients/deluge.py, mylar/webserve.py
- IMP: Updated Experimental RSS Feed URL (might solve some timeout issues)
- IMP: Fixed Experimental returning garbage with the titles (tries to clean it up as best as it can)
- FIX: Changed ``encodestring`` to ``decodebytes`` for deluge torrent adding due to depreciation in python 3.9.x
- FIX: Manually post-processing files that had an invalid issue number would cause a traceback and halt post-processing
- FIX: Prowlarr indexers includes (correctly) the full *UTF encoding markup in the filename - caused nzbname creation to go funky
- FIX: ``Skipped2Wanted`` option on series detail page would incorrectly notify/mark in some cases
=> various fixes - see comments for more details

mylar/getcomics.py
FIX: incorrect resolving of  ``%s`` when doing queries against GC (would do a query for * instead of specific query)
=> FIX: Incorrect resolving of GC query variable

mylar/PostProcessor.py
=> FIX: Apparently Snatche isn't a proper word

data/interfaces/default/config.html, mylar/search.py, mylar/search_filer.py
- FIX: torrent torznab would not be identified as such causing problems with searching, downloading, etc.
- FIX: try to properly generate an id from torrent url (alternate method)
- FIX: Remove 32P from config page (*cri…
=> FIX: torznab related woes

data/interfaces/default/upcoming.html, data/interfaces/default/weeklypull.html, mylar/updater.py
- FIX: Mismatched status on pull-list clickable back to Upcoming / Mismatched table to show possible explanation
- FIX:  DB Updater adding identical series during check
=> FIX: Mismatched status on pull clickable link back to Mismatched table, FIX: Updater could add identical series

mylar/PostProcessor.py
=> FIX: # was duplicated on some post-processing notifications

mylar/webserve.py
If CV is unresponsive/down/unable to respond properly, it would return a boolean value into a for-next loop which caused a traceback error in python, and either a 500 error in the GUI or a continually ``processing`` message.
=> FIX: bool iteration error when not able to query CV

mylar/importer.py
resulted in stale series.json files.
=> FIX: series.json would not update on refreshes called from the weekly pull

mylar/helpers.py
=> FIX: changeStatus API endpoint to work with annuals

mylar/config.py, mylar/getcomics.py, mylar/search.py
``Experimental`` vs ``experimental`` when writing to db that was supposed to be unique tied to a unique id - she go boom, Jim.
=> FIX: (#1114) experimental error due to camelcase when unable to search

mylar/search_filer.py
Copy of the [original pull request](https://github.com/mylar3/mylar3/pull/1119) made against the `master` branch against the `python3-dev` branch.
Thanks for the quick feedback!
=> Compare length of result substring against length of comic name

mylar/PostProcessor.py
- FIX: issues that aren't on the watchlist, but are part of a story-arc & snatched via DDL would not post-process
- FIX: post-processing pre-script should run prior to metatagging not after.
=> FIX: one-off story-arc issues snatched via DDL would not post-process, FIX: Pre-script moved to prior to metatagging

mylar/PostProcessor.py
_run__extra_scripts was not running shell scripts.
=> starting my shell collection

mylar/config.py, mylar/helpers.py
=> FIX: locmove would not reset, and locmove was doubled in the config

data/interfaces/default/config.html, mylar/PostProcessor.py, mylar/cmtagmylar.py, mylar/search.py, mylar/series_metadata.py, mylar/webserve.py
IMP: setdefaultvolume GUI option
FIX: Gotify notif incorrect module call
FIX: setdefaultvolume honor in series.json
FIX: pass correct volume thru when metatagging
=> setdefaultvolume add to GUI metatagging options, make sure to honor in other modules

mylar/carepackage.py
- FIX: add carepackage version to output to track versioning
- FIX: remove 32P carepackage checks
- FIX: make sure the *nabs values are being parsed correctly
- FIX: new way to call pip that's more platform agnostic
=> FIX: carepackage updates

data/interfaces/carbon/css/style.css, data/interfaces/default/css/style.css, mylar/carepackage.py, mylar/req_test.py, mylar/versioncheck.py
- FIX: pip req check would fail on docker installs and not display anything
- FIX: installation type now included in carepackage generation
- FIX: suppress unrar output during test check
- FIX: always return a value for release_messages, even if it's just empty/blank
=> FIX: config warnings/info section -  fixes and updates

data/css/style.css, data/interfaces/default/history.html, mylar/search.py
- FIX: duplication of downloads in history table (going forward)
- IMP: Provider column added to history table and bettter column lengths
=> FIX: duplication of downloads in history table, IMP: Provider column addition to history table

mylar/api.py
Just readding the endpoint change as per the previous PR that we reverted due to conflicting commits within the PR.
=> FIX: Made 'addStoryArc' API call more descriptive in it's return (@WillowMist)

data/interfaces/carbon/css/data_table.css, data/interfaces/carbon/css/jquery-ui.css, data/interfaces/carbon/css/style.css, data/interfaces/default/css/data_table.css, data/interfaces/default/css/style.css
Adjusted column spacing
Fixed progress bar containment
White + for carbon pull page
=> CSS fixes/adjustments

mylar/PostProcessor.py
FIX: Post-processing notifs/logging of annuals would take series name as opposed to annual name (annual integration) (ie. ``Justice League`` as opposed to ``Justice League 2022 Annual``)
=> FIX: Post-Processing notifs of annuals displaying incorrect series name in some cases

data/interfaces/default/comicdetails_update.html, data/interfaces/default/css/data_table.css, data/interfaces/default/css/style.css, data/interfaces/default/queue_management.html, data/interfaces/default/storyarc_detail.html, data/interfaces/default/storyarc_detail.poster.html
- FIX: (#1270) issue count missing on main page (default theme)
- FIX: Storyarc issue count not showing on detail page
- FI:X Unable to properly load resizeimage function on storyarc detail page when image present
- FIX: Manage DDL showing duplicate buttons
- FIX: Secondary watermark on series detail page was not aligned within column
=> guess who? css who! that's who! Woo ?

mylar/PostProcessor.py
=> Fypo correction (#1297)

mylar/config.py
=> FIX:(#1284) trailing slash in url if not present

mylar/helpers.py, mylar/webserve.py
=> FIX:(#1295) Make sure to reset the sort counter if no series are present after removing from watchlist

mylar/__init__.py
Take 2 of #1341. Fixes one imprint mapping and adds a missing one.
=> Fix imprint mappings

mylar/config.py, mylar/versioncheck.py
This adds Kubernetes detection to the docker detection.
Inspired by #1241
=> Added kubernetes detection

README.md
=> failure on linkage

mylar/filechecker.py, mylar/search_filer.py
- FIX: downloading annuals would work intermittently (usually not working thru GC)
- FIX: post-processing would not match annuals properly and ignore them during a run
=> annual patches to make them work

data/interfaces/default/manage.html
=> FIX: correct wording about worker repair (@OddBloke - #1417)

mylar/weeklypull.py
=> feat(mass-add): Do not add series if in ignored publisher list

data/interfaces/default/storyarc_detail.html, data/interfaces/default/storyarc_detail.poster.html
- disables enter key if Banner Image field is empty
- disables banner upload button if field is empty
- will only accept field if value starts with ``http``
=> FIX:(#1432) story arc banner upload field could accept null values in error

mylar/importer.py
as reported in discord - possible fix, but not entirely sure as could not replicate
=> FIX: occasional db conflict during issue updates in previous PR (#1446)

mylar/filechecker.py
=> FIX: error on startup for windows users

mylar/getcomics.py
Also, when downloading packs:
on the Manage DDL page, will now show the full filename of the pack instead of ``series #issuenumber`` (ie. ``Superhero # 1``)
=> FIX: pack downloads were broken due to previous PR variable change

mylar/getcomics.py
=> Move gzip header to fix tempermental ddl

mylar/getcomics.py
apparently can't spell digital anymore...
=> FIX: DDL would not gather links due to digital typo and incorrect refence to variable

mylar/search.py, mylar/search_filer.py
- FIX: feedparser would blow up (traceback error) when parsing non-digital dates in some cases
- FIX: ``StoryArcs -> Search For Missing`` button would traceback when initiating the search
=> FIX: feedparser traceback error, FIX: SearchForMissing arc button fix

data/interfaces/default/base.html, mylar/__init__.py, mylar/filechecker.py, mylar/helpers.py, mylar/importer.py, mylar/updater.py, mylar/webserve.py
FIX: (#1510) Adding by comicid would result in error in GUI, but series would still add successfully.
FIX: (#1508) Typo in logger when viewing a Paused series that contained annuals
FIX: (#1507) .Black and .White numbering exceptions added
FIX: When popup appeared, would open all hidden/minimized options in config page if tab was open
FIX: Infinity numbering vs Infinity in series name fix
=> bunch of late night fixes...(#1510)(#1508)(#1507) and some more

data/interfaces/default/comicdetails_update.html
Following guidelines, this time the PR goes against `python3-dev` branch.
=> Fixed typo

mylar/cv.py
previous PR change muckered up the logistics...
=> FIX: booktype would fail to detect non-print volumes properly

data/interfaces/default/index-alphaindex.html, data/interfaces/default/index.html
forgetting a formatted div tag will do that....
=> FIX: (#1523)(#1530) Horizontal alignment of footer on index page

mylar/downloaders/pixeldrain.py, mylar/webserve.py
Thanks to :  
- @halkeye ( #1540 )
- @raph521 ( #1552 )
=> PRs valid but were too far out of sync for simple changes - manually added

mylar/helpers.py
also removed some redundant code related to pull date calculations
=> FIX: initial load of pull would have start of week incorrect as the current date

data/interfaces/default/upcoming.html, mylar/webserve.py
Resubmit against fresh python3-dev for merging, plus changed "All" to "Tier-1" on the button prompt for clarity.
=> Added ability to force queue a subset of Wanted issues

mylar/search.py, mylar/webserve.py
- Change download queue for selected items to be-non manual to respect downloaded skip check
- Fixed a couple of existing checks on search queue build
=> Tweaks for existing download checks on searches

mylar/nzbget.py, mylar/webserve.py
reminder to myself to always test prior.
=> FIX: NZBGET would throw an invalid port error on testing/sending due a previous related PR

mylar/sabnzbd.py
verified happening on 4.4.1 - during a download, if direct unpack is enabled within SAB (it's on by default), the status returned in the api is always Extracting until the download has fully completed. This isn't a problem usually if the file is small ( < 50mb ), but on marginally larger files ( > 75mb)  the status sticks longer than it takes to poll against and results in abandoned downloads.
This introduces a retry-delay count based on the size of the download to ensure that there's enough time for the download to finish the extracting phase (basically the entirety of the download) before mylar gives up.
=> FIX: SAB downloads would get stuck due to Direct Unpacking sticky status until completion

mylar/sabnzbd.py
Suggested quick fix for #1664.
Could put a more robust failure state to drop out if it happens on roundtwo, but it will go on to fail in later passes anyway and this is to account for what I believe to just be a blip in SAB responses.
=> FIX: Check for valid storage response from SAB

mylar/cmtagmylar.py
The goal here was  a fix for failed cbr to cbz conversions in cases where the cbr contains a directory. 
- Add check_cbr_has_folders() to detect CBR files with internal folders
- Add flatten_cbr() to extract and repack CBR files without folder structure
- Detect and use system unrar for extraction
- Skip CBR2CBZ conversion for files already in CBZ format
- Properly handle flattened CBR files in the conversion pipeline
=> Fix CBR to CBZ conversion for archives with folder structure

data/interfaces/default/comicdetails_update.html
Someone asked for this in discord, and I'm sure I've seen people asking for it before.
=> Enabled remembering page size filter on Comic Details page
