mylar3/mylar3

data/interfaces/default/config.html
mylar/PostProcessor.py
mylar/config.py
mylar/filechecker.py
mylar/getimage.py
mylar/helpers.py
mylar/notifiers.py
mylar/webserve.py

- Added config options for sending cover in notif for Telegram & Pushover. 
- Instead of using URL, will extract downloaded cover and send that as a notif, or fallback to no cover if in error. 
- Updated seriesdetail page cover extraction to use new getimage code (no file extraction).
- Removed several INFO logging lines when filechecking.

merged #2409 from mylar2.  Updated to use extract_image instead of URL call.

---

mylar/webserve.py

Updated from sha224 to sha256 for no real reason.

FIX:(#55) Specify encoding for Generate APIKey

---

mylar/getimage.py
mylar/helpers.py
mylar/webserve.py

- Added possible fix for invalid padding when encoding images. 
- Updated cover retrieval to account for files that don't have images starting at a 0/1 digit. 
- Make sure IssueName is properly encoded when displaying

image extraction fixes

---

mylar/webserve.py

Occasionally maxyear ends up as a float, probably a result of an automagic string conversion. Casting it to int makes range() not throw an exception.
I ran into it with a value of 2004.0 which casts nicely

cast maxyear as an int for range()

---

mylar/webserve.py

Testing torrent clients would crash with the old way of importing the torrent module.
More explicit import lets you test torrent clients successfully.

fix imports for torrent clients

---

data/js/plugins.js

If a page doesn't have a dataTable class then defining a custom sorting method throws a javascript error. The Manage page is has no dataTable when it loads and throws this error today.

define custom sort methods only if there's a dataTable element

---

mylar/auth32p.py
mylar/rsscheck.py
mylar/search.py

- (#111) fix traceback error on download of torrent via 32p
- fixed no results from 32p over-riding actual search results in some cases
- removed legacy key checks when using auth mode

various 32P fixes

---

mylar/weeklypull.py

Fixes this crash
```
Job "Weekly Pullist (trigger: interval[4:00:00], next run at: 2020-02-25 21:11:59 UTC)" raised an exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
File "/app/mylar/mylar/weeklypullit.py", line 30, in run
weeklypull.pullit()
File "/app/mylar/mylar/weeklypull.py", line 427, in pullit
newtxtfile.write(str(shipdate) + '\t' + str(pub) + '\t' + str(issue) + '\t' + str(comicnm) + '\t' + str(comicrm) + '\tSkipped' + '\n')
TypeError: a bytes-like object is required, not 'str'
```

Fix writing strings in binary mode crash

---

mylar/filechecker.py

Sometimes issue number is None, which makes the regex crash.

Fix crash with null issue number.

---

mylar/rsscheck.py

Fix handling of magnet links, especially from torzab search.
If the url is a magnet link or if the url redirects to a magnet link, don't write a file with the torrent contents, since there aren't any. Just pass the magnet string along to the downloader.
This PR is a sibling to #105

fix for magnet links, especially from torznab

---

mylar/webstart.py

The way many ajax buttons are implemented in mylar is through server side redirects. This is nice and easy but if the server doesn't peep at the headers to see that SSL is terminated somewhere else, it redirects to http instead of https  and causes a UI error.
The button "worked" it just doesn't redirect to the proper success notification and appears to have failed until you do a manual client side refresh.
This fixes about a hundred apparent bugs for people using SSL termination.

Auto proxy support

---

mylar/webserve.py

If the restart queue is empty, pressing the restart queue button crashes.
Simple fix to prevent that.

Fix restart queue empty

---

mylar/filechecker.py

the argument 'i' is never a regex and yet sometimes it contains regex special characters like parentheses. In this case it usually crashes because the parens are unmatched, but there's a chance it could behave strangely by interpreting matched parens or other characters as a regex instruction.
Change this to a string replace operation to fix the crash or undefined behavior
Currently testing.

Fix regex parsing crash parsing search results

---

Mylar.py

1. Add traditional PID-based pidfile: I saw the pidfile was being created with the word "pid" in it, rather than the parent PID of the daemonized process, which is the tradition. I think maybe pidfile was simply used as a lockfile, but there's no reason to limit ourselves to that since the daemonize code is limited to non-win32.
2. Add a check to determine if an existing pidfile is stale (meaning it represents a process that no longer is running).  This function does nothing unless you're on linux with a /proc fs - in which case it will check  if the given pid exists currently.  If not, we know it's a stale PID file and we return True.  If it DOES exist, it checks the cmdline to make sure the commandline is a python process.  If python isn't in the cmdline, we know it's a stale pidfile. …

pidfile tweaks

---

mylar/webserve.py

If the restart queue is empty, pressing the restart queue button crashes.
Simple fix to prevent that.
Replaces #130, #136, #139
Manually rebased

fix restart

---

data/interfaces/default/config.html
mylar/torrent/clients/rtorrent.py
mylar/webserve.py

- FIX:(#138) RTorrent test option would always default verify to True.
- Sending torrents via RTorrent would default the verify option to False.

Rtorrent verify option fixes

---

lib/comictaggerlib/comicvinecacher.py
lib/comictaggerlib/main.py

In doing so, the entire settings module becomes available to use throughout CT instead of having to reload the config whenever settings need to be loaded in a new module.

globalize the SETTINGS module variable

---

lib/rtorrent/connection.py
mylar/torrent/clients/rtorrent.py

- FIX:(#138) Using ruTorrent instance with no SSL would still test for SSL and fail. 
- Using ruTorrent instance with SSL enabled would work incorrectly when given an http url.

ruTorrent SSL fix

---

mylar/filechecker.py

Problems were occurring when the series had a given year in it (ie. ```2000 A.D.```), and the issue number was greater than 1900 (or ended in 19/20), with no year in the title. This should fix that.

attempt to reliably parse filenames with issue numbers greater than 1000.

---

mylar/config.py

On Windows systems, resolving to ~ to create the CT settings folder would not work properly and would cause an error on startup/using CT. Will now default to Mylar DATA_DIR if it cannot create the directory on a Windows system

On Windows OS, could not write to the ~ of the user when writing CT files

---

mylar/notifiers.py

- end result is that if the max retries error occurs the post-processing queue locks up and won't post-process anything else.

FIX: fix for telegram notifs failing due to max retries exceeded

---

mylar/config.py
mylar/search.py

Should fix #217,
Possible fixes for: #210, #212 
Might also resolve some previously stated problems regarding high CPU usage.

FIX: fix for simultaneous searches firing off when done using different search methods

---

mylar/versioncheck.py

If git wasn't in environment path, would accept failed output as a valid response and attempt to use that as commit/branch information

FIX:(#225)  Invalid response when running updater on git installations

---

mylar/carepackage.py

-Fails to perform cleanup of temporary files and causes an error on Windows systems due to locked files.

FIX:(#231) Carepackage failure on windows due to locked files

---

mylar/librarysync.py

I had a few broken links in my comic share that were causing Mylar to stop processing my comics.
To reproduce:
cd /path/to/comics
ln -s /path/to/nothing
[python]
for fn in os.listdir('/path/to/comics'):
if fn == 'nothing':
exist = "Yes" if os.path.exists(fn) else "No"
print(f'''Filename {fn} exists: {exist}''')
Without my patch, it chokes on the getsize call.

Fix crash if Mylar sees book that's a symlink to a nonexistant file

---

mylar/config.py

Provider_Order sequence would not be respected when loading from the config.ini. 
Seems Mylar would tend to reorder based on code priority vs ini priority. 
This PR should load the values from the config.ini properly, as well when items are removed/added while keeping the existing order as much as possible (ie. new provider enabling would add to the end of the existing order, removal of provider would move everything higher in the order sequence to be lowered accordingly).
Reference is from a forum post [here](https://forum.mylarcomics.com/viewtopic.php?f=8&t=2257)

FIX: provider_order would not respect ini settings 

---

data/interfaces/default/importresults.html

error due to extra, out-of-place table rows. solution was found here: https://www.datatables.net/forums/discussion/comment/112718/
error causes datatables to not load, which prevents any of the useful features for sorting, paging, etc.
3rd times a charm?!

Fix datatables error on ImportResults

---

mylar/helpers.py
mylar/sabnzbd.py

clean up some issues in the nzb queue monitoring which:
1.  Fix the broken reference in the log line within helpers.py which was breaking things, and forcing the re-queueing to fail
2.  Fix the endless loop:
In this case, if an nzb was no longer found in the queue within sab, it'd be loop endlessly looking for it.   Solved by adding a quick check to see if the nzb we're looking for exists in the result set at all, and if not, return with a new status and log it.  Eliminating the while loop altogether seems fine, as it was only ever looping through the same result from sabnzbd history.

Eliminate endless loop in sabnzb queue

---

mylar/search.py

check issue numbers for none before converting to int. This a dumb patch which just prevents the crash. I didn't look hard upstream to figure out why one of these values got set to None 
```
15-Apr-2020 04:26:10 - INFO :: mylar.NZB_SEARCH.514 : ThreadPoolExecutor-0_0 : Shhh be very quiet...I'm looking for XXXXXXXX XXXX issue: 10-02 (2019) using ddl [RSS].
Job "RSS Feeds (trigger: interval[6:00:00], next run at: 2020-04-15 10:26:02 UTC)" raised an exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
File "/app/mylar/mylar/rsscheckit.py", line 110, in run
mylar.search.searchforissue(rsscheck='yes')
File "/app/mylar/mylar/search.py", line 1776, in …
```

fix a search crash

---

mylar/search.py

If DDL was only provider enabled, and search is started by using the ```Skipped2Wanted``` option on the series detail page- would throw back an error indicating that no search providers were enabled.

FIX:(#260) Skipped2Wanted option wouldn't search if using DDL

---

mylar/getimage.py
mylar/helpers.py
mylar/search.py
mylar/webserve.py

- fixes some encoding errors that were present from py2 resulting in traceback errors.
- updated the auto-snatch queue to include the ComicID & IssueID
- with above change, direct post-processing can be accomplished instead of relying solely on filename parsing.
Also updated getimage retrieval to allow for:
- always taking the jpg that ends in a 0 or 1, dependent on which is lower
- remove common scanner jpgs from being included (ie. zzzXXXXX, or similar)
- make sure to allow for Series that may start with the letter z so they're able to be displayed.
- include the RawImage in the json response (which might be abit too much payload, and adds slightly more time to the overall execution). This might need to be fine-tuned later at some point.

updates auto-snatch Rtorrent remote torrent downloads to work in python3 + small image retrieval improvements

---

mylar/notifiers.py

Fixing typo in discord notif init

Fixing typo in discord notif init

---

mylar/search.py

If any of DDL, 32P, experimental were enabled, subsequent searches would not be fully searched against, if at all in some cases (as per forum issue).

FIX: checked_once not being reset between searches

---

data/interfaces/default/comicdetails.html
mylar/__init__.py
mylar/filechecker.py
mylar/filers.py
mylar/search.py
mylar/webserve.py

- FIX:(#279) Option to ignore booktype matches for specific series when searching
- FIX: (#183) Added Force Type dropdown to series detail page - can change the Edition/Type of a given series to any of the available options (TPB, One-Shot, Digital, Print). 
- When using Force Type option above, if ```$Type``` is enabled in Folder Format configuration, will rename existing folder to new Edition/Type as per the Folder Format string, to show the change at the folder-level

booktype enhancements

---

mylar/filechecker.py

- (#275) Series with 'of <number>' in the title would incorrectly parse
- improved regex to keep square brackets intact during parsing
- date checker will now accept YYYY-MM-00 as a valid date entry

filechecker fixes (#275 fixed + square bracket regex addition)

---

data/interfaces/carbon/css/jquery-ui.css

Fixes for #307
I changed the colour styling to match for failed blocklist provider and indirectly fixed the delete comic prompt too.
Tested in Firefox and Chrome on Windows 10.

Fixed blocklist provider styling

---

mylar/webserve.py

This is a partial fix for the importer stalling and throwing a DB exception due to datatype. There are upcoming updates that will address #337 and #149 fully, but this is the simplest of ones to patch to get the importer working.
This will allow it to continue in most cases, but subsequent errors are a possibility as a result. Note that this *might* also fix the problem of manual intervention returning a blank page in some cases.

FIX:(#337)(#149) Partial fix for stalled importer throwing a DB exception

---

mylar/getcomics.py

If you have a size value which contains mixed values (i.e 1.7GB//512MB) only the MB value was handled correctly.

 FIX: Always replace GB (fixes mylar3#343)

---

lib/comictaggerlib/comicapi/comicarchive.py
requirements.txt

unrar-cffi is now an optional component. Will work with either unrar-cffi if installed, or default back to included rarfile if it's not installed.
If it's already installed, Mylar3 will use it when unraring from within ComicTagger. Otherwise, will default back to the included rarfile module.
If using the rarfile module, either the unrar binary HAS to be in your environment PATH, or you need to locate the .ComicTagger directory path (either in the mylar root, or in the Mylar user's home directory). Once located, edit the ```settings``` file and set the ```rar_exe_path``` to the FULL PATH to the unrar binary (ie. /usr/local/bin/unrar).
Note: wiki updated to include the above with additional instructions as required [here](https://github.com/mylar3/mylar3/wiki/unrar-cffi-vs-included-rarfile)

Removed unrar-cffi component from ComicTagger and requirements.txt

---

mylar/filechecker.py

When dealing with filenames that have '100-Page' or the like in the series title, would incorrectly take the numeric as the issue number in the cases where an issue number was not present (ie. One-Shot).

fix for page numbers parsing incorrectly when included in filename

---

mylar/PostProcessor.py

Per #400 Thank you @SenorSmartyPants

FIX: correction to popen call returning bytestream

---

mylar/getcomics.py

As descibed here the search aborts if only "/" is used to split sizes on getcomics:
#413
Please let me know if this fix works for you.
@evilhero:
As described in this PR (https://github.com/mylar3/mylar3/pull/414) I cleaned up the commits.
Best regards
miracle152005

fixes #413 also check if "/" is in size instead of only checking "//"

---

README.md
lib/comictaggerlib/settings.py

- fix for unrar binary not being detected on new installations due to checking for the wrong binary (rar != unrar). If the unrar (or RaR can also be used on Windows systems) is not in the system path, then the ```rar_exe_path``` field must be set in the .ComicTagger/Settings file to the full path to the given binary.
- updated README to include unrar requirement for CT (as per above re: rar_exe_path)

FIX: fix for unrar not being properly detected on new installations

---

mylar/PostProcessor.py
mylar/filechecker.py
mylar/search.py

When searching for series that would match as an alternate naming possibility - would incorrectly take the alternate naming match instead of ensuring no other matches exist with the correct series titles (ie. Empyre would match to Empyre - Avengers, etc)
When trying to post-process issues similar as above - if no watchlisted series were present, but the series existed on the arc watchlist, would incorrectly take the wrong series as the matching title.
This PR should resolve all the matching problems as indicated above - however, in doing so, any any alternate series titles that are discovered when file parsing (not the ```Alternate Search Name``` field), are discarded atm in order to try and minimize incorrect matches going forward.

(#432) Fixes search & post-processing related issues between similar named series on the watchlist

---

mylar/filechecker.py

If the filename would contain a hyphen during a filecheck/rescan - it would get flagged as a possible ```alt_match``` due to how there are lots of various naming schemes.  This fixes the error so that things can keep on trucking.
The ```alt_match``` was implemented in a previous PR in order accommodate search results/post-processing returning values that might possibly be a long-shot of a match, but was mistakingly being taken as the priority match.

FIX:(#449) hyphens in filenames during refresh/rescan causing error

---

mylar/rsscheck.py

Feedparser 6.0.0 breaks backwards compatibility with one of the module calls Mylar uses.
This just checks the version and if it's less than 6 it keeps the current calling method, otherwise it modifies it slightly so that the module can be correctly called using 6.0.0.

FIX:(#451) Fixes FeedParser 6.0.0 not working, will still work with < 6

---

mylar/filechecker.py
mylar/rsscheck.py

- FIX:(#449) hyphens in filenames during refresh/rescan causing traceback error
- FIX:(#451) Fixes FeedParser 6.0.0 not working, will still work with < 6

python3-dev merge

---

mylar/PostProcessor.py
mylar/webserve.py

Also included : quick fix for viewing downloaded annuals on the series detail page (via the **i** icon) - just added the correct table.

FIX:(#471) Fix for annuals not being post-processed

---

mylar/webstart.py

moved 
`tools.sessions.timeout = options['login_timeout']`
to somewhere it would actually work :D

fixed setting the tools.sessions.timeout value

---

mylar/filechecker.py

When searching / post-processing / file-checking, would incorrectly parse some items in the filename as if they belonged to an issue exception listing which resulted in the issue number being incorrectly parsed and thereby not match ever.

FIX:(#496) file parser problem when performing a search / post-processing / recheck.

---

data/interfaces/carbon/css/style.css
data/interfaces/default/css/style.css
data/interfaces/default/logs.html
mylar/__init__.py
mylar/helpers.py
mylar/search.py
mylar/webserve.py
mylar/weeklypull.py

- Try / Except handling around the main aspects of the search and weeklypull modules, which should make every traceback therein not queue-ending (meaning even after the error, the searches can continue as if they never happened).
- Added a special popup in the Logs tab (```History``` / ```View Logs``` / ```Exceptions / Tracebacks```) where all recorded tracebacks are logged - ability to view specifics, delete entries, and view log snippets pertaining to that specific traceback error, just prior to the error occuring.
- Fixed a problem with DDL provider being lower-cased which might have resulted in some missed searched calls.
- Formatted entire search.py file with black to conform to a soft-line limit of 88.
- linted search.py with flake8

IMP: Traceback/exception handling added to better handle crashes during search

---

mylar/__init__.py
mylar/helpers.py
mylar/webserve.py

Older installations (upgrades from mylar2), might still having an exceptions table in db which would cause the needed table to not be created on startup.

FIX: changed table name from exceptions to exceptions_log

---

mylar/search.py

SABNZB was no longer able to download because the address to get the nzb from was not correct.

fixes #528 SABNZB Path calculates mylar address incorrect

---

data/interfaces/default/opds.html

Fix for a mako error when trying to use opds:
CompileException: Fragment 'for link in opds['links']: <% linktitle = '' if 'title' in link: linktitle =' is not a partial control statement in file '/volume1/mylar/share/mylar3/data/interfaces/default/opds.html' at line: 16 char: 1
fixed by reverting some of the original file formatting from a previous version of opds.html

Fix Mako error in opds.html

---

data/interfaces/default/logs.html
mylar/getcomics.py
mylar/search.py
mylar/webserve.py

- FIX: fix for DDL throwing CF challenge errors and killing the queue. This will not fix the errors (as that is due to the use of an external module), but it will not kill the queue now.
- FIX: searches doing an extra loop for non-loopable providers (ie. DDL, experimental)
- FIX: removed timeout after search for non-loopable providers
- FIX: fixed traceback GUI dialog so that it can delete specific entries
- FIX: ugly monkeypatch to exception GUI display so screen doesn't have to be refreshed
- IMP: black + flake8 done to getcomics.py

DDL fixes for traceback logging + other related items

---

mylar/search.py

More specifically, when searching via RSS, incorrect search terms were being searched for that would not match against providers tagged as either [localhost] or [nzbhydra], resulting in 0 rss hits for issues that were present in the db cache.

FIX:(#538) RSS cache would not be referenced properly against tagged newznab providers

---

mylar/filechecker.py
mylar/webserve.py

- FIX:(#548) Properly detect variations of unicode dashes and represent them as a single dash when comparing/matching/etc, 
- FIX: Pull-list may show every issue on the pull as Snatched instead of Skipped

Adjust for variations of unicode dashes & pull list problems with one-off's

---

mylar/api.py
mylar/webserve.py

- IMP: API method **changeStatus** added to allow for mass changing of status' from a specific status to another, by comicid:
- change **status_from** of every issue in series to specified **status_to**
- if no comicid specified will mark ALL issues in EVERY series from status_from to specific status_to
- required fields: **status_to**, **status_from**. Optional: **id**  (which is the ComicID if applicable)
- IMP: API method **recheckFiles** added to allow for batch rechecking of series based on comicid:
- allow either individual / bulk recheck Files based on ComiciD
- multiples are allowed as long as in a list: {'id': ['100101', '101010', '20181', '47101']}

IMP:(#257) added changeStatus and recheckFiles to API

---

mylar/webviewer.py

If there is not-encoded `#` symbol in filename, browser won't open file.

Added encoding filenames for webviewer

---

mylar/rsscheck.py

If CF was active when the RSS fires off with DDL enabled, it would cause the RSS feed to traceback due to not getting back a valid response. 
This was in part due to an incorrect formatting reference in the logger, but will now also indicate that CF might be the possible cause of the 503 in the logs for reference.

FIX: DDL RSS Feed would error out when a 503 is returned (CF is active)

---

mylar/search.py

When searching for a One-Shot with an issue number of not 1 and comparing search results, would not correctly match to the given issue number (that isn't an issue 1).

FIX:(#565) Search results incorrect matching on One-Shots with numbering not equivalent to 1

---

mylar/findcomicfeed.py
mylar/search.py

- IMP: (#568) Added additional filters to experimental search to allow for header formats of: YYYY-MM-DD-(Indie/Marvel/DC) [nn/nn]
- FIX: providers that don't require search iteration due to issue numbering (DDL, experimental) will now stop being used after the first iteration of a search term (ie. 1, 01, 001 will stop it after the first iteration of 1 since it's not needed).

FIX:(#568) additional filters added to experimental search, FIX: fixed removal of issue iteration for non-iterating providers

---

data/interfaces/default/queue_management.html
mylar/getcomics.py
mylar/webserve.py

- FIX: corrected incorrect url check for DDL in order to get some additional values when parsing search results for matching values.
- FIX: if a DDL download failed during a download, or never initiated properly (probably due to CF popping up), filename would be invalid and it would not give available options in the GUI
- FIX: corrected Failed color status in DDL history view

DDL GUI patches & DDL parsing adjustment for additional values for search matching

---

Dockerfile
Mylar.py
data/interfaces/default/config.html
mylar/config.py
mylar/webserve.py

This should add the ability to run backups at startup through a config option instead of just a command line option. This will allow people like myself to use the LinuxServer.io image and maintain DB backups. This can be accomplished by restarting the container on a schedule, which is not ideal but is doable.
I'm getting errors when using the Dockerfile, so I have not been able to test this change.
```
ERROR: unsatisfiable constraints:
git-2.24.3-r0:
breaks: world[git=2.24.1-r0]
```

Add a config option for backups during startup

---

mylar/helpers.py
mylar/sabnzbd.py

- FIX: fix for SABnzbd not returning enough results when searching history for matching nzo_id during CDH. Will either return last 200 results now (as opposed to 5-10), or will directly query against the specific nzo_id (sabnzbd 3.2.0Beta1+)
- FIX: removed indirect apikey references when logging relevant information related to sab.
- FIX: changed some INFO logging to DEBUG, and removed a few others (related to sabnzbd responses)

FIX: fix for CDH (SABnzbd) not finding nzo_id when querying sab history

---

mylar/search.py

My "RSS Feeds" Job, as seen on Manage -> Activity / Jobs (Schedulers), always appears to be Running after the initial / successful run of the job after startup.  Looking at the code, the "[RSS-FEEDS] Watchlist Check for new Releases" (mylar.search.searchforissue(rsscheck='yes')) call in rsscheckit.py does not reset mylar.SEARCHLOCK which causes the subsequent job to do nothing but sleep.

FIX: "RSS Feeds" Job Stuck Running

---

mylar/PostProcessor.py

- FIX:(#608) When using the [__ISSUEID__] switch in a filename during a manual post-processing with multiple files, would stop after the 1st file was post-processed.
- FIX: When using the [__ISSUEID__] switch in a filename, the resulting filename in some cases would contain an extra space prior to the extension.

fixes for using [__ISSUEID__] in filename during manual post-processing

---

mylar/__init__.py
mylar/updater.py

During a ReCheck Files of series that has a large issue base, the actual writing of issues to the db was very slow - especially when the issues were not present (ie. not Downloaded).
As an example, 
For a series of ~2230 issues, of which 2196 were not present.
before:
issue_status_writing took 0:00:18.884588
after:
issue_status_writing took 0:00:00.029606
This might need some further optimisation and/or testing, but from my limited testing it seems to be working far quicker than expected.

IMP: improved speed of ReCheck Files

---

mylar/helpers.py

'queue' error was due to NZBGet not actually having that field in the response being retrieved.

FIX:(#626) When using CDH with NZBGet, would cause a 'queue' error

---

mylar/db.py
mylar/updater.py

Small improvements to the previous ReCheck PR:
- replaced iteration with executemany in regards to writing data to the db with relation to Status (ReCheck Files).
- instead of a separate connection to the mylar.db, will use existing connection via the db module. This should help prevent any database locking regarding this aspect.
- added the executemany option to the db module - which allows said execution over iteration, which should increase write times as well.
- both the above were done in regards to the ReCheck Files option only. Other aspects may/may not see improvements if used there.

IMP: small improvments involving ReCheck Files

---

mylar/webserve.py

This PR only affects the view for the non-alpha main page (alphaindex = False)
Previously sorting the Have column on the main index page would result in sorting by completion percentage, which would incorrectly sort.
This fixes it so that it now sorts by Total Issues descending, then by Have Issues ascending - which results in items in a more logical sequence (ie. so 0/400 comes before 0/1, both of which come before 1/34).

FIX: fixed sorting of Have column on non-alpha index

---

mylar/mb.py

In some cases, CV might not have available fields populated in the XML being returned from a search query due to being new series present in the listing, which causes search results for a query to finish generating (and thus no display to GUI). 
ATM this can happen for images, but this might have to be extended / refined if more fields end up being blank in order to avoid errors.

FIX:(#632) Add a try/except around image retrieval in case image is not yet present on CV

---

mylar/getcomics.py
mylar/search.py

- IMP: Use alternate search patterns with DDL until some valid matches are found. Used #382 as the main basis for the change (thnx @Micket).
- IMP: auto-correct DDL search query if series contains either ':' or '/'.

DDL: Use alternate search patterns as needed, and auto-correct query based on specific characters 

---

mylar/config.py
mylar/mb.py

- Renamed blacklisted_publishers variable to ignored_publishers. Will auto-convert any existing values on startup.
- Updated how Mylar interprets the bad_definitions settings so it doesn't create extra commas as values when removing/replacing old variables.

IMP: Renamed blacklisted_publishers to ignored_publishers

---

mylar/getcomics.py
mylar/search.py

- Check booktype before attempting to snatch non-booktype related issues with DDL (ie. issue vs TPB). This can occur when items are part of a pack and they add TPB to the listing, in some cases the issues are on non-resolvable links so Mylar attempts to snatch the TPB links since they're active, but they weren't being searched for.
- Ignore weekly pack matches for DDL single issue searches. Since Mylar can't process 0-day packs as of yet from DDL, there's no point in retaining it as a search result.

IMP: check booktype before attempting to snatch DDL links, IMP: Ignore weekly packs in DDL results

---

mylar/__init__.py
mylar/config.py
mylar/cv.py
mylar/helpers.py
mylar/importer.py
mylar/mb.py
mylar/updater.py
mylar/webserve.py

Currently in order to keep watchlisted series up-to-date, Mylar goes from oldest last update time to newest - so the oldest titles will always get refreshed first. This has several problems with it - namely that it has to poll CV every 5 minutes so the backlog doesn't get huge, it's constantly updating old series that might not need/have an update, it's just inefficient.
The new method introduced in this PR:
- will poll CV for issues that have been updated in the last 8 weeks initially on first startup (this is configurable, ```DB_BACKFILL``` can be set to a higher numeric if required). However larger datasets will require more time to back-fill.
- if the results comes back as more than 1500 entries for the 8 week period, it will only query for the last 1500 items based on the update_date …

IMP: Changed the entire method Mylar uses to maintain series being up-to-date

---

mylar/locg.py
mylar/weeklypull.py

Due to CV not updating items until the following week in some cases, and because the weekly pull changes to the new week on Sundays, some issues on the Wanted list from the previous week would not get updated until the given series was either manually refreshed or a new issue came out in subsequent weeks.
This PR tries to ensure that the stragglers (ie. updates on CV that happen after the pull changes over), are updated and displayed correctly on the given week's pull. This will update the current week, as well as the previous week's pull-list with any relevant issue information changes.

IMP: When the weekly pull job runs, it will now recreate the pull for previous week as well

---

data/interfaces/default/comicdetails.html
mylar/importer.py
mylar/webserve.py

- FIX: fix for latest storedate being used for publication run, if the value is 0000-00-00
- FIX: when adding a series via the Search option, would throw back an error related to metadata location when trying to load the relevant series
- FIX: fix for low chance of duplicates appearing on main watchlist page when using the filter option

FIXES:  adding a series via the Search causing an error, incorrect value used for publication run, duplicates when using filter on main page 

---

mylar/importer.py
mylar/webserve.py

Mylar would over-write a series.json file if it was already present in the series directory - regardless of it was generated by Mylar or outside of Mylar. This occurred regardless of it was via a new add / Refresh Series / clicking on the series.json indicator.
Will now load series.json metadata for description first and use that, before attempting to load the description field from the dB. The description loaded into the GUI for display purposed on initial load will be prioritised with json data being first, edited description db data second, followed by CV data.
Note that this only applies to the description field. Odds are pretty good that at some point additional fields will have to be added to the check so that hand-generated information is prioritised over automated.

FIX:(#686) Fix for existing descriptions in series.json files being hammered if pre-existing.

---

mylar/updater.py
mylar/webserve.py

- FIX: When editing the issue date via the series detail page, could not revert to CV data if manually edited (will now revert on 0000-00-00 entry)
- FIX: if an invalid date of 0000-00-00 was present during a refresh, would incorrectly mark as Wanted if Auto-Want Upcoming was enabled
- FIX: when adding a series via the search, during the load sequence Mylar would attempt to load the series page and fail (causing a GUI error), if the Comic Location path wasn't saved to the Db yet

FIX: Allow for 0000-00-00 in Edit field for Issue Date (to revert), FIX: adding series would cause a 500 error due to series.json check

---

mylar/findcomicfeed.py
mylar/search.py

-IMP: (FIXES #664, #670, #689) changes experimental search so it doesn't query multiple times for the same issue, instead does it all in one query
- IMP: allows for possible disabling if query returns are invalid

Experimental search query changes

---

data/interfaces/default/comicdetails.html
mylar/webserve.py

- FIX: when editing description for a series, would fail to initially load up existing description for editing (would be a blank canvas)
- FIX: Clicking on OK after editing would not update description

series.json fixes that broke when editing a series description

---

Mylar.py
data/interfaces/default/base.html
mylar/versioncheck.py

- IMP: will now indicate if docker is being used in the GUI
- IMP: disable built-in updater and update-checks if docker is being run
- IMP: run versioncheck prior to starting the webinterface to avoid error message if trying to view webpage after initial startup too quickly  (wasn't finished starting up fully).

some docker patches to make things simpler

---

mylar/PostProcessor.py
mylar/sabnzbd.py

When using CDH and the SABnzbd directory option, searching the active queue if the directory option was not in the same path would result in files not being found error message. This also occured during post-processing as the directory option was not taking certain factors into account (same idea as the history check basically).

FIX: fix for SABnzbd directory option not being properly determined

---

data/interfaces/carbon/css/style.css
data/interfaces/default/css/style.css
data/interfaces/default/weeklypull.html
mylar/updater.py
mylar/weeklypull.py

- IMP: Improved mismatch detection when polling from backend and comparing against Watchlist.
- IMP: Added a ```Mismatched``` status to the weekly pull to indicate when a title on the watchlist has incorrectly been auto-matched (based on comicid) and the backend data is incorrect (assigned a specific series the wrong comicid).
- IMP: Safety check implement that will now check the date of the given issue in the pull that it's matched up to, to ensure it's in the correct week, as well as that the booktypes correctly match up.
- IMP: digital issue should now be more accurately detected as being such instead of mistakenly matched to their printed counterparts when both digital and print editions of a particular series are available.

Pullist improvements

---

mylar/updater.py

it seems that we will just drop out of processing entirely if a single TPB/one-shot is found.
This will just skip over the issue leaving the warning in tact.

Fixed not importing any issue's if one TPB/one-shot found

---

mylar/PostProcessor.py
mylar/__init__.py
mylar/helpers.py
mylar/importer.py
mylar/search.py
mylar/updater.py
mylar/webserve.py
mylar/weeklypull.py

- FIX: When deleting Annuals from a series (annual tracking is on), will now remember deleted items so refreshing the series does not re-add them repeatedly
- FIX: Due to the inclusion of the Deleted field in the annuals table, have to change select statements involving annuals so as to not look at Deleted items

FIX: Do not re-add previously deleted annuals from a series when annuals are enabled.

---

data/interfaces/carbon/css/data_table.css
data/interfaces/default/searchresults.html

- FIX: (carbon) When viewing search results items already in library would have differing coloured bars, simplified down to one color instead of alternating
- FIX:(carbon) Search results print editions green colouring not so neon green

FIX: carbon interface search results row colouring

---

mylar/weeklypull.py

This is to try to ensure that any late updates done by CV after the previous week has flipped to the current week will be caught and updated accordingly. This will only affect requests when the current week is requested (ie. startup check, manually re-creating of current week, scheduled weekly update).
Should fix #709 coupled with a previous update which changed how Mylar polls CV for outdated series information.

FIX: extend current week pull's refresh to include previous week

---

mylar/webviewer.py

note: not sure how this will resolve on reverse-proxies - it should be fine since even if the value in the config.ini doesn't have a trailing ```/``` we add one by default.

FIX: fix for cbr files not rendering in webviewer on Windows systems

---

mylar/__init__.py
mylar/updater.py
mylar/webserve.py

This is the first part to this.
This will keep track of the last time the files were checked within a directory for each series via the ```FilesUpdated``` dB field.
It will basically run a ```ReCheck Files``` during a series detail page load only if any files have been modified/created/deleted within the given series directory. It will only trigger if anything has changed - if nothing has changed it will not do a ReCheck.
The 2nd(ary) part is to have it automatically monitor the folders themselves (outside of the GUI), and update the check accordingly, but be dependent on running only if something has changed.

IMP: monitor series directory changes via FilesUpdated field.

---

data/interfaces/carbon/css/style.css
data/interfaces/default/css/style.css
mylar/webserve.py
mylar/weeklypull.py

- FIX: (add.it.all) mass_publishers config.ini value would grow exponentially under certain conditions
- FIX: (add.it.all) Submit button for add.it.all option would render on top of drop-down
- FIX: (add.it.all) Not setting any publishers and enabling auto-add would not save the value to config resulting in auto-add not being enabled

add.it.all fixes

---

mylar/getcomics.py

Quick hack to get DDL working again - will push out a better technique in the next day or two that will provide a better option if CF happens to be up.
note. cfscrape is dead and doesn't work anyways at this point - next PR will probably remove it.

FIX: hacky fix for DDL not downloading due to CF

---

mylar/PostProcessor.py
mylar/__init__.py
mylar/helpers.py
mylar/importer.py
mylar/updater.py

- added ```intLatestIssue``` to the comics table.
- created a function to add values to ```intLatestIssue``` on startup so it should never be null.
- added to importer and weeklypull check so that the ```intLatestIssue``` will be populated when added / updated via the pull.

FIX: fix for previous PR which broke post-processing issues that matched to multiple volumes but not currently published

---

mylar/config.py
mylar/search.py
mylar/webserve.py

in GUI:
- use ```,``` to separate torznab categories
in config.ini
- use ```#``` to separate torznab categories
The PR does the above and converts between the two as required so all the user will see is the categories separated by ```,``` within the GUI - but it is stored with ```#``` as the category separators.

IMP:(#777) Allow for multiple categories within torznab configuration

---

mylar/PostProcessor.py

Due to the previous PR's regarding post-processing where extra checks were added to ensure that the issue was pegged to the correct series, ongoing series that had previous issues that weren't on the pull would not post-process.

FIX: Attempt to fix post-processing of previous issues of a series that is present on the pull-list

---

mylar/__init__.py
mylar/api.py
mylar/config.py
mylar/importer.py
mylar/series_metadata.py
mylar/updater.py
mylar/webserve.py

- Allow for writing / reading of series.json v.1.0.1 metadata
- Added config.ini boolean option ```seriesjson_file_priority```:
- ```True```: will prioritise series.json data for displaying & writing description data field.
- ```False```: will priortise dB data for displaying & writing description data field.
Fall-back method is the opposite of the selection if available.
- Broke out the seriesjson update module from webserve.py into it's own individual module (```series_metadata.py```)
- Added ```refreshSeriesjson``` and ```seriesjsonListing``` API endpoints ([docs here eventually](https://github.com/mylar3/mylar3/wiki/API-Documentation))

IMP: Update of series.json metadata to allow for 1.0.1 versioning, IMP: Added api calls for listing and updating seriesjson

---

data/interfaces/default/config.html
mylar/api.py
mylar/config.py
mylar/search.py
mylar/webserve.py
mylar/webstart.py

- added ```listProviders```, ```addProvider```, ```delProvider``` and ```changeProvider``` API endpoints (see https://github.com/mylar3/mylar3/wiki/API-Documentation).
- fixed newznab ```verify ssl``` field in the GUI.
- fixed API calls so they wouldn't generate cherry tracebacks whenever an API endpoint was used.
- multiple categories are now allowed for newznab entries.

IMP: Added listProviders, addProvider, delProvider and changeProvider API endpoints

---

data/interfaces/default/storyarc_detail.html
data/interfaces/default/storyarc_detail.poster.html
mylar/cv.py
mylar/filechecker.py
mylar/webserve.py

- FIX: Added ability of filechecker to properly detect filenames containing a volume in the format of (YYYY-)
- added in some additional volume handling of annuals being detected incorrectly btwn CV deck and CV description.
- Changed formatting of annuals on story arc detail page so that they are named as ```Series Volume Annual (Year)``` so the naming is more consistent with series titles (which are ```Series Volume (Year)```.
*note that on a story arc detail page, the annual will not be properly highlighted as belonging to a particular series (when annual integration is enabled), however the status will still be properly shown (it's a display issue).

FIX:(#770) Annuals, when annual integration is enabled, would not be linked up properly when viewing a related story arc

---

mylar/updater.py
mylar/weeklypull.py

- When annual integration is enabled and the annual is present on the weekly pull (might also be during different scenarios), would incorrectly think that a previous refresh failed and attempt to recreate the entire annual series during the db update interval check (which is every 24hrs or on every restart).
- linking of annual to series (with annual integration enabled) would incorrectly show the comicid to the annual not the series that the annual is tied to which would result in a dead link.

FIX: attempted fix for annual directories being created incorrectly along with pull-related annuals

---

data/interfaces/default/config.html
mylar/config.py
mylar/filers.py
mylar/helpers.py

- depreciate the ```$Annual``` variable as an option for use with Folder Format.
- will remove any existing occurrence of ```$Annual``` within the Folder Format scheme.

FIX: Depreciate the annual field as an available option for Folder Format

---

mylar/locg.py

When not manually recreating the pull-list (ie. the auto-scheduler method), it would only refresh the exsiting table with new data - which could create extra / repeated entries depending on issue changes to the pull-list.
This will just ensure that the existing weekly table for the given week, gets wiped out prior to putting the new data in so that it's never considered 'stale'.

FIX: weekly pull would not properly recreate the current week via the autoscheduler method.

---

mylar/config.py
mylar/cv.py

When the db_updater runs, it takes a date range - the last time the updater was successfully ran and the current date. It uses that as the start-end range when requesting issue data from CV. 
As of  yesterday, CV did something to one specific issue that was posted/updated at a specific time which would cause an error - both in the API and on the CV website itself. If Mylar was requesting a set of data within that range, CV would return an xml error response and no updates would occur. This would deadlock as Mylar would try later to retrieve the same data range, but fail again due to that one specific issue.
This PR does a few things:
- creates 2 new config entries: ```problem_dates``` and ```problem_dates_seconds```.
- ```problem_dates``` is a list variable which holds any bad issue …

FIX: fix for CV erroring out when the db_updater was requesting a range that contained bad data on CV

---

mylar/findcomicfeed.py

Would sometimes allow headers that contained ```[01/33]``` as part of a valid result - which it shouldn't be since that's not pertaining to the actual title. This PR just makes sure that those items gets rejected so that the subsequent set would be accepted and used.

IMP: added detection of header values containing blocks for experimental results

---

data/interfaces/default/upcoming.html
mylar/webserve.py
mylar/weeklypull.py

- FIX: force annuals to use release name instead of trying to modify the name (annuals will now correctly appear in Wanted table)
- FIX: fixed upcoming table so it updates accordingly when new issue data is present (issues with issue data will be removed from the Upcoming table and into the Wanted table. Upcoming table will only show issues with no issue data present yet).
- FIX: corrected some whitespace in weeklypull.py

FIX: annuals not properly showing as their release name in Wanted table, FIX: Upcoming table not updating

---

mylar/PostProcessor.py
mylar/filechecker.py
mylar/search.py

- FIX: ``2021 Annual`` would not post-process, search, or match during file rechecks
- IMP: auto-add normalised annual naming as an AlternateSearch when searching for a ``2021 Annual``

FIX: 2021 annuals would not be post-processed, searched or matched against

---

mylar/series_metadata.py

note that the series would still be added just fine - since the series.json creation happens at the end of the process.

FIX: series.json creation would error when adding new series

---

data/interfaces/default/upcoming.html
mylar/updater.py
mylar/webserve.py

- FIX: Wanted page not displaying due to annuals being listed as individual watchlist items and also within series (via annual integration)
- IMP: Added warnings to logs and listing of actual annuals that are duplicated as both series & individual listings (see above)
- FIX: Corrected possible incorrect counts related to annuals during file rechecks
- FIX: Corrected possible incorrect pathing for Archived issues during file rechecks

FIX: Wanted page not displaying, FIX: during rechecks - incorrect annual counts and incorrect Archived pathing 

---

data/interfaces/default/config.html

- moved ``cbr to cbz ONLY`` option to ``Conversions`` section on the same tab
- if ``enable metagging`` is enabled, then ``cbr to cbz`` is enabled by default and locked (cause you need to have it)
- if ``enable metatagging`` is disabled, then ``cbr to cbz`` becomes unlocked if it was and enabled (unless the config.ini option is for it to be enabled)
- placeholders left in place for future file conversions when available (_cbz --> cb7_) and image conversions ( _jpg/png --> webp_)
- fixed some incorrect click options for CDH

IMP: break out the CBR TO CBZ ONLY option in the config under it's own section as Conversions

---

data/interfaces/default/comicdetails.html
mylar/api.py
mylar/filers.py
mylar/helpers.py
mylar/importer.py
mylar/readinglist.py
mylar/updater.py
mylar/webserve.py

if the ``multiple_dest_dirs`` option was being used, and the ``destination_location`` was within a subdirectory off of the main directory (ie. it was in a ``$publisher/series`` type of format) the multiple_dest_dirs option would fail to pick it up properly
This PR addresses that problem, in addition to building it out so that it will now accept for series locations under the multiple_dest_dirs folder:
- series folders as titled exactly under the destination location
- series folders if matching to the current folder format (even if the destination location folders are titled differently)

IMP: allow multiple_dest_dirs option to work with subdirectory strutures

---

mylar/__init__.py
mylar/updater.py
mylar/webserve.py

- FIX: (#846) memory leak on Manage Issues page
- FIX: on startup, make sure to remove problem IDs from comics table
- FIX: Updater would fail if ``LastUpdated`` field was not present

FIX: (#846) memory leak, FIX: removal of invalid ComicID's on startup, FIX: Updater invalid field patch

---

data/interfaces/default/comicdetails.html
data/interfaces/default/config.html
data/interfaces/default/searchresults.html
mylar/PostProcessor.py
mylar/__init__.py
mylar/cv.py
mylar/filechecker.py
mylar/filers.py
mylar/helpers.py
mylar/importer.py
mylar/mb.py
mylar/search.py
mylar/updater.py
mylar/webserve.py

- IMP: Add  to ``$Imprint`` to allowable Folder Format fields
- IMP: Imprint text field added to series detail page for manual editing if needed
- IMP: subset booktype from TPB to TPB/GN/HC
- IMP: when editing the directory in the series detail page for a series, will now check to see if both the parent and parent-of-the-parent directories exist - if not it will create them prior to renaming the existing folder
- FIX: fix publisher_imprints not properly checking file stale date 
publisher_imprints also had an update which changed Marvel Comics to Marvel, and Image Comics to Image - so the file state date check update is necessary to pull the new json.

IMP: Imprint as an Folder Format field, IMP: GN/HC added to available booktypes, FIX: stale date check was invalid

---

mylar/helpers.py
mylar/importer.py

- FIX: incorrect image references on Manage page if imageURL is None
- FIX: ImageUrl not being generated correctly during add/refresh of series due to invalid if statement

fixes for imageURL being incorrectly referenced/created during series add/refresh

---

mylar/updater.py
mylar/webserve.py

- FIX: DBUpdater would not run every ``backfill_timespan`` interval (default 10 minutes) when updating large backlog queue, 
- FIX: Status' not indicated as Running in Activity/Jobs tab

FIX: DBUpdater would not run when performing large backlog queue, FIX: Status' not updating in Activity/Jobs tab

---

Mylar.py
mylar/config.py
mylar/search.py
mylar/webstart.py

- FIX: allow for enclosures URL as opposed to just using link field in provider response
- IMP: option to toggle cherrypy logging via the config.ini (```cherrypy_logging```)

FIX: allow for using enclosures URL in provider response, IMP: toggle cherrypy logging via ini

---

mylar/helpers.py
mylar/search.py

- FIX: newznab test option would incorrectly append ``api`` endpoint in some situations
- FIX: reworked newznab api url in search to better detect url's with ``api`` endpoint already included

FIX: api url appending 'api' incorrectly when testing newznab and searching (in some cases)

---

lib/comictaggerlib/cli.py
mylar/PostProcessor.py
mylar/cmtagmylar.py
mylar/versioncheck.py
mylar/webserve.py

- IMP: allow metatagging to write out reading order sequence when dealing with multiple arcs
- FIX: downloading non-watchlisted arc issues would fail to be detected if files were not within a folder (ie. a single file)
- FIX: corrected user-agent url
- FIX: RSS scheduled job was always in a running status, even if it was not

IMP: reading order sequence writing out for multiple arcs for an issue, FIX: post-processing failing on individual non-watchlisted arc issues

---

data/interfaces/carbon/css/data_table.css
data/interfaces/default/comicdetails.html
data/interfaces/default/css/data_table.css
data/interfaces/default/index.html
data/interfaces/default/weeklypull.html
mylar/webserve.py

- IMP: ``search-4-missing`` option added to series detail page
- FIX: catch invalid name when deleting series via Delete Series
- IMP: ``+mark`` option added for watchlisted series that have issues in a Skipped status on weeklypull
- IMP: series issues in Skipped status on the weeklypull colour-graded now
- FIX: correct some invalid css
- FIX: adjust column layouts for better fit on index page

IMP: search-4-missing option added (back), IMP: watchlisted series not being distinguished if in a Skipped status on weeklypull, FIX: CSS fixes

---

data/interfaces/default/upcoming.html
mylar/PostProcessor.py
mylar/updater.py
mylar/webserve.py

- IMP: ``Opposite Tier`` option via dropdown on Wanted page (change Tier of selected items)
- FIX: Post-processing of annuals that don't belong to a series (with annual integration enabled)
- FIX: Better handling of provider notification errors during post-processing
- FIX: If an ongoing title didn't exist on a previous week's pull (due to no valid pull info), would reject for post-processing
- FIX: Annual checking for series would take V as the issue year (if VXXXX present) resulting in mismatched annuals for a series with multiple annual volumes

IMP: Opposite Tier added to Wanted page, FIX: Post-processing of annuals not belonging to series

---

data/interfaces/carbon/css/style.css
data/interfaces/default/history.html
data/interfaces/default/storyarc_detail.html
data/interfaces/default/storyarc_detail.poster.html
mylar/PostProcessor.py
mylar/search.py
mylar/updater.py
mylar/webserve.py

- FIX: Post-processing of story-arc issues that were not on the watchlist, and was a single file download, would incorrectly join the file path resulting in an invalid path.
- FIX: Post-processing of story-arc issues that belonged to multiple storyarcs will now be flung into multiple arc directories (if applicable)
- FIX: Post-processing of story-arc issues would not update status (history table) when completed 
- FIX: ``Clear Status`` button was not available in story-arc detail page to clear existing status of an issue to Skipped
- FIX: better spacing of some table elements in story arc detail page
- FIX: history page retry button would not work
- IMP: story arcs will now be shown (and clickable) if applicable to the given item the history page

FIX: multiple fixes for story-arc post-processing, IMP: clear status option in story arc details, FIX: history page

---

mylar/cv.py

- FIX: imprint published on exact start/end year of imprint publication run, would fail to detect as an imprint
- IMP: imprint check will now compare by month if series was in same year as imprint publication start / finish before matching

FIX: Imprints matching problems related to start/end years of imprint

---

data/interfaces/default/history.html
data/interfaces/default/weeklypull.html
mylar/PostProcessor.py
mylar/search.py
mylar/webserve.py

- FIX: one-off items were not being shown in history table (will now have an additional ``One-Off`` tag)
- IMP: clicking on a one-off item in the history page will load up the respective week & year in the pull and scroll to the issue
- FIX: weekly pull had available options for one-offs that were not supposed to show
- FIX: change variable ``mode`` to ``smode`` in search module to avoid python naming conflict

FIX: History page updates for one-off issues

---

Mylar.py

Incorrect reference of ``errno.EXIST`` corrected to ``errno.EEXIST``

FIX: (#892) incorrect errno reference

---

mylar/PostProcessor.py

I noticed the following post-processing error logs for StoryArc grabs
```
29-Sep-2021 16:01:08 - WARNING :: mylar.Process.1185 : Thread-174 : [Exception: local variable 'watchmatch' referenced before assignment] Unable to properly match up/retrieve issue number (or volume) for this [CS: {'StoryArc': 'The Killing Joke', 'StoryArcID': '40503', 'IssueArcID': '40503_8984', 'ComicName': 'Batman: The Killing Joke', 'DynamicComicName': 'batmankillingjoke', 'ComicPublisher': 'DC Comics', 'Publisher': 'DC Comics', 'IssueID': '119383', 'IssueNumber': '1', 'IssueYear': None, 'ReadingOrder': 1, 'IssueDate': '1988-06-30', 'Status': 'Snatched', 'Location': None}] [WATCHMATCH: {'SeriesYear': '1988', 'LatestDate': '1988-06-30', 'ComicVersion': None, 'ComicID': '19967', 'Publisher': 'DC Comics', 'Total': …
```

Reference correct variable when post-processing story arcs

---

mylar/locg.py
mylar/webserve.py
mylar/weeklypull.py

- When WS was offline, would cause Mylar to not update the pull - but in some cases it would actually wipe the pull-list prior to attempting to retrieve new data which resulted in an empty pull. When WS came back online, it wouldn't mark the appropriate issues as Wanted thereafter due to the wipe. Will now check if WS is online and data is available prior to wiping the table entries.
- When WS was offline, would return a status code 522 due to being behind CF now - which changed the response action that happens on error which resulted in some weird data mismatches. Will now also update the WS footer status.

FIX: better handling of pull-list data when WS is offline/unavailable.

---

mylar/__init__.py
mylar/helpers.py
mylar/versioncheck.py
mylar/webserve.py

- FIX:(#900) ``check_github`` and ``check_github_on_startup`` not being honoured if both were set to ``False`` (would still hit github)
- FIX: Schedulers displaying incorrect status (either always Running, or always Waiting)

FIX:(#900) check_github and check_github_on_startup not being honoured, FIX: Schedulers displaying incorrect status

---

mylar/search.py

When the Auto-Search fired off (or a Force Search was done), it would queue up items that were tiered (tier 1). If it was a tier2 item, it would actually perform a threaded search for that issue - resulting in simultaneous requests firing off for different issues (when it shouldn't have done anything for tier2). 
This PR fixes it so if it's a tier1 item, it will be queue as per normal. If it's a tier2 item, it will be ignored - since the Auto-Search / Force Search should only be searching against Tier1 items.
Note that the Tier2 aspect of searching for RSS only when the scheduler kicks off will probably have to be subsequently fixed...

FIX: Auto-Search/Force-Search would add Ttier1 items to queue, but also search simultaneously for Tier2

---

mylar/sabnzbd.py

Post-processing calls would fail to properly detect the location of the downloaded file due to incorrect joining of paths when the SABnzbd Directory is the same as the final location where SABnzbd downloads to (ie. the destination path returned from SAB is in the same path as the SABnzbd Directory location provided within Mylar).

FIX: adjust post-processing location if SABnzbd download location is the same as Directory Location

---

mylar/api.py

invalid api key reference check.

FIX: sending to client via CDH would fail with empty nzb error

---

mylar/rsscheck.py

This fixes uTorrent and magnet links. addFile results in an error with magnet links, addurl is what is needed. I also added some more debug lines related to magnet as I was struggling with this before. IDE cleaned up trailing whitespace automatically.
I am currently using this, so it does work.
> Hope this is what you were looking for this time. Clean patch on a fresh fork of the python3-dev branch. Let me know if I am still misunderstanding this here.

Fix magnet support for uTorrent

---

mylar/sabnzbd.py

When searching the active SABnzbd queue would search nzo_ids by name using the search field (which searches nzb names), instead of using the nzo_ids field. 
Not sure if this was a new addition in SAB, or if it was always there - but this fixes endless looping of downloads when the queue is large.

FIX: filter SABnzbd queue by nzo_id instead of search name

---

mylar/rsscheck.py
mylar/search.py

- Corrected so that instead of a boolean string (which will always return True), will be the boolean of an integer of a string.
- Also fixed Experimental hitting non-https for some reason when retrieving RSS feed.

FIX: (#929) Verify taken from config when searching was being passed as a string instead of a boolean

---

data/interfaces/default/config.html
mylar/PostProcessor.py
mylar/cmtagmylar.py
mylar/nzbget.py
mylar/webserve.py

- FIX: NZBGet would not work if the password contained a ``?``
- FIX: NZBGet Test Connection option in the configuration page was not working correctly
- FIX: Updated Annuals Integration option in configuration to better indicate what enabling/disabling does and changed color
- FIX: SABnzbd section of configuration would not show Test Connection unless CDH was enabled - reworked the layout abit
- IMP: Removed all references/checks to SABnzbd being 0.8.0 or greater and the info line about ComicRN in the configuration
- FIX: Removed ``IssueArcID`` logging warning when post-processing issues that were not part of a story-arc.
- FIX: Removed logging of CT metatagging output/errors (it's handled with better wording already)

FIX: nzbget url change to allow for ? in passwords, FIX: various configuration page fixes

---

data/interfaces/default/comicdetails_update.html
mylar/webserve.py

- IMP: series detail page will only recheck files on page load if any file has been modified instead of incorrect counts (improved check)
- FIX:(#944) Metatagging annuals would result in error via series detail page
- IMP: quick scan during manual metatagging to ensure proper location is being used (in case of sub-directories, secondary locations, etc)

FIX:(#944) Metatagging annuals would result in error, IMP: series detail rechecking files incorrectly on page loading

---

mylar/config.py
mylar/filechecker.py
mylar/webserve.py

- FIX: corrected series page recent file check logic so it works with Windows-based paths and not run on every page load
- FIX: Added ``SCAN_ON_SERIES_CHANGES`` to enable/disable at a global level recent file check on series page load
- FIX:(#947) None-type error during manual run

FIX: series page recent file checks, FIX:(#947) None-type error on manual scan

---

data/interfaces/carbon/css/style.css
data/interfaces/default/base.html
data/interfaces/default/css/style.css
data/interfaces/default/searchresults.html
data/interfaces/default/storyarc.html
data/interfaces/default/storyarc_detail.poster.html
mylar/__init__.py
mylar/mb.py
mylar/webserve.py

FIX: Adding a story arc would error due to te previous PR which changed how new Additions were handled
FIX: Sorting by column / filtering for searchresults was broken
FIX: story arc images would always resize to default even when a different sizing method was chosen & saved
FIX: ``clear`` option from story arc detail page would not remove all instances of previous images
FIX: reversed ``Add this Comic`` and ``Edit``positioning wise so row doesn't jitter when Edit is clicked
IMP: Store filename for CoverImage for storyarcs in db for easier / proper referencing
IMP: searchresults for storyarcs moved to a separate js function
IMP: mylar-logo will rotate when searchresults (main search dialog/ storyarcs) are being queried until results page displays

Fix for StoryAdd error and various searchresults problems

---

mylar/helpers.py
mylar/weeklypull.py

because of the year change, but January 1st, 2022 falls at the end of week 52, Mylar tries to flip to week 0 cause of the year change. This will return 0 results from the backend (even though week 1, 2022 will line up fine). So this just tells Mylar whenever it sees week 0, 2022 to assume it's week 52, 2021.
Note that this probably won't be an issue once the week flips on Sunday to week 1, 2022.  But this will at least remove the incorrect option from displaying for some.

FIX: monkey patch for week 0/2022 pull-list

---

mylar/weeklypull.py

If loading the pull for week 1 (the current week) for the first time, would error on attempting to retrieve the previous week which was mistakingly being calculated as week 0, 2022 instead of week 52, 2021.

FIX: week 0 attempting to be retrieved on initial loading of pull

---

Mylar.py
data/interfaces/default/comicdetails_update.html
data/interfaces/default/config.html
data/interfaces/default/maintenance_base.html
data/interfaces/default/maintenance_mode.html
data/interfaces/default/manage.html
data/interfaces/default/weeklypull.html
mylar/PostProcessor.py
mylar/__init__.py
mylar/api.py
mylar/config.py
mylar/cv.py
mylar/filechecker.py
mylar/filers.py
mylar/getcomics.py
mylar/helpers.py
mylar/importer.py
mylar/maintenance.py
mylar/maintenance_webstart.py
mylar/mb.py
mylar/readinglist.py
mylar/rsscheck.py
mylar/rsscheckit.py
mylar/search.py
mylar/search_filer.py
mylar/updater.py
mylar/webserve.py

IMP: vast improvement in RSS searching time (refactored)
IMP: maintenance-mode GUI mode with progress indicators, resume and isolated web GUI during upgrade path when upgrading db (as well as progress in CLI)
IMP: DDL downloads will get the ``[__ISSUEID__]`` attached temporarily to filename to lessen chance of problems with naming problems
IMP: Break out search matching functionality from search module into it's own module
IMP: (refactor) Breaking out allows DDL items to be verified for matches during queries saving hits & time
IMP: Priority Alternate Search Name added - use !! instead of ## to denote priority vs normal
IMP: Provider-search delay (global setting) is now honoured on a per provider basis and is persistent across restarts.
IMP: Skipped2Wanted will now take both issues & …

Here. Hold my sink. And all of this.

---

mylar/cmtagmylar.py
mylar/notifiers.py

Added a notify function to the metatagger. Also modified discord notifications to add yellow error embed for these errors. Other notifications **should** work, but I wasn't able to test them.

Add notifications for errors with the metatagger

---

Mylar.py
mylar/config.py
mylar/filers.py
mylar/maintenance.py
mylar/search.py

- FIX: (#1011) If Experimental provider was enabled, Mylar would fail to start.
- IMP: Added ``backup_location`` and ``backup_retention`` as config.ini values to better control where & how much backup files are retained.
- IMP: Backups are now rolling backups based on the ``backup_retention`` value (default of 4 files). Will only keep the X most recent files of each in the ``backup_location`` if specified (if not will be in the root of the mylar installation).
- IMP: Altered the ``-b`` switch to allow for ``-b ini`` or ``-b db`` for ini and db only backups respectively. Just using ``-b`` by itself will back up both.
- IMP: Backup of config.ini will occur when config schema is updated. Backup of mylar.db will occur when db schema change is required or database data needs altering.
- FIX: …

FIX:(#1011) Experimental provider error on startup, IMP: Changed how ini & db files are backed up

---

mylar/search.py
mylar/webserve.py

Also fixed the ``OppositeTier`` option on the Wanted page not properly setting changing the date for Tier2-->Tier1 conversion.

FIX: searches would not adhere to their given Tier

---

mylar/getcomics.py
mylar/search_filer.py
mylar/updater.py

-FIX: No need to store cookies for non-CF GC atm - so stop trying to save them
-FIX: if booktype was invalid/None, the rss search parser/matcher would cause an error on a valid match otherwise
-FIX: annuals would not update in some cases due to traceback

various small fixes - see comments

---

mylar/cmtagmylar.py

DIR not FOLDER.
for buckle's sake.

FIX: incorrect variable reference during metatagging

---

mylar/updater.py

Stupid thing - this error caused annuals to not populate if annual integration was enabled and thereby not appear on the series page as well as not showing/linking to the series on the pull (as well as being marked as Wanted).

FIX: annuals would not link on pull, causing them to not populate at all

---

mylar/Failed.py
mylar/PostProcessor.py
mylar/findcomicfeed.py
mylar/getcomics.py

- FIX: Experimental search would throw traceback on searching for print versions of issues with no file name
- FIX: If file already exists when DDL goes to download and resume isn't enabled, would cause traceback
- FIX: Variables not formatted in a logger line within the failed module
- FIX: If file already exists during post-processing without the ``[__ISSUEID__]`` (but has it within the original filename) in the same location (ie. DDL) - would throw a FileExistsError and halt post-processing queue

FIX: couple traceback errors w/ experimental & GC, FIX: GC file already exists error

---

Mylar.py
data/interfaces/default/storyarc_detail.html
data/interfaces/default/storyarc_detail.poster.html
mylar/config.py
mylar/importer.py
mylar/webserve.py

- IMP: Add unwatched series from Arc to watchlist
- FIX: logging error on non-EN systems during maintenance resultling in non-operational bootup
- FIX: Remove ``Read Sync`` and ``Clear File Cache`` from StoryArc detail pages as they're non-working
- FIX: indicate Data directory check on startup, instead of saying comic directory (misleading)

IMP: Add unwatched series from Arc to watchlist, FIX: logging error on non-EN systems during maintenance

---

mylar/filechecker.py
mylar/webserve.py
mylar/weeklypull.py

- FIX: SSE display during DBUpdate would have a None for year
- FIX: Remove ``year_check`` logging during file scanning

FIX: DBUpdate notification/logging variable incorrect, FIX: remove unnecessary logging 

---

data/interfaces/default/storyarc_detail.html
data/interfaces/default/storyarc_detail.poster.html
mylar/PostProcessor.py
mylar/rsscheck.py
mylar/updater.py
mylar/webserve.py

- FIX: Storyarc detail options (``grab`` and ``retry``) would not work with story arcs with an ``'`` in the title
- FIX: (Post-Processing) Fixed DDL (or files tagged with the ``[__issueid__]``) path location probelms 
- FIX: (Post-Processing) One-offs / storyarcs  in conjunction with using ``[__issueid__]`` file tag 
- FIX: (Post-Processing) Tidyup after Post-Processing would fail to cleanup remnants with a path error
- FIX: Scheduler displaying as ``Running`` when it's not
- FIX: Remove some unnecessary logging lines

FIX: Storyarc detail options fix, FIX: Post-Processing DDL problems, 

---

data/css/style.css
data/interfaces/carbon/css/style.css
data/interfaces/default/base.html
data/interfaces/default/comicdetails_update.html
data/interfaces/default/css/style.css
data/interfaces/default/upcoming.html
data/interfaces/default/weeklypull.html
mylar/api.py
mylar/helpers.py
mylar/webserve.py

- IMP: added ``regenerateCovers`` API endpoint to allow for regeneration of series covers in cache folder [see here](https://github.com/mylar3/mylar3/wiki/regenerateCovers)
- IMP: Added reason and additional information to Mismatch table on Wanted page / Upcoming section to try to briefly explain why the mismatch
- FIX: ``default_dates`` would not be honoured when trying to set default view on series detail page for Store / Cover dates
- FIX: check version results could not be seen in default interface due to white color
- FIX: fix upcoming table in Wanted page css layout

this is the rick to your roll

---

mylar/PostProcessor.py

Both fixes relate to post-processing and DDL downloads (or any file with the ``[__issueid__]`` tag).
Extra logging added to get some additional info during path conversions since some users are mentioning that the ddl downloads are staying in a Snatched status and not post-processing.

FIX: typo when parsing DDL post-processing, FIX: additional logging during path conversion with DDL

---

mylar/PostProcessor.py

DDL downloads would carry a renamed path value of None for some reason when removing the ``[__issueid__]`` from the filename, causing the post-processing to not be post-processed for the given file. 
Hoping that this resolves it by testing for a None value on return of the rename that uses pathlib, and if it's None, use the os.replace method instead.

FIX: Attempt to fix ddl issues with removing & renaming issueid from file when present

---

mylar/search.py

Getting packs returned in a search query would throw an error with the pack detector - was taking the variable from the wrong dictionary.

FIX: (#1085) packs in search results would cause key error

---

data/interfaces/default/queue_management.html
data/interfaces/default/searchresults.html
mylar/webserve.py

- also set queue management page to display 25 results by default.

FIX: invalid query in search box would never finish rendering results page

---

mylar/__init__.py
mylar/config.py

default value if not manually set will use a semi-recent UA.

FIX: configurable user-agent (cv_user_agent) via config.ini

---

mylar/versioncheck.py

due to .LAST_RELEASE not having write permissions (only when using master branch).  
Not a biggie - put within a try/except for the win.

FIX: hotio docker image would fail to start cleanly - resulting in error when viewing pull

---

Mylar.py
mylar/__init__.py
mylar/maintenance.py

IMP: ``-cp`` (``--clearprovidertable``) added to maintenance CLI. Command will drop the provider_searches table in case the table becomes corrupt with bad data or multiple providers causing a startup error 
FIX: cleaned up the args.parse calls on startup
FIX: adjusted the os.execv list on restart so it calls the proper arguments

IMP: -cp (--clearprovidertable) added to maintenance CLI, FIX: cleaned up the args.parse on startup

---

Mylar.py
mylar/__init__.py
mylar/config.py
mylar/maintenance.py

- FIX: (#1125) config port value not being honoured
- FIX: ``-cp`` switch would not run correctly
- IMP: config value of ``clear_provider_table`` (``True``/``False``) to allow clear the table on startup for docker users (will auto-change to ``False`` if previously set to ``True`` on successful run (ie. provider table is cleared).

FIX: (#1125) config port value not being honoured, FIX: -cp switch would not run correctly

---

data/interfaces/default/config.html

``cbr2cbz_only`` would be set to ``True`` in the config.ini as a result of changing GUI config options in the GUI in a random way. Having this enabled would result in no tagging taking place, just conversion.
Will now be locked down so that if cbr2cbz is enabled, metatagging is disabled. If metatagging is enabled, cbr2cbz will disable itself with a warning line on the page that says ``CBR to CBZ conversion is automatic with Metadata Tagging enabled``.

FIX: cbr2cbz only would be enabled in some unwanted cases, resulting in no metatagging

---

mylar/filers.py

Would only occur if you have the ``$Publisher`` variable in your **Folder Format** and on  Windows.
Since *nix can handle the trailing period, this only fixes it for Windows.

FIX: (Windows) If publisher ended with a period, would fail at creating directory

---

mylar/cdh_mapping.py
mylar/config.py
mylar/nzbget.py
mylar/sabnzbd.py

Also added in a config.ini option for SABnzbd to allow for increasing the historycheck delay from 5s (default currently) to a manual value ``SAB_MOVING_DELAY = 5``. 
This is necessary if SABnzbd has a final download directory that is not local to the OS (remote) and requires more time to complete the process than the atypical 5 seconds.

FIX:(#1132) CDH would not map correctly between different OS'

---

mylar/filers.py
mylar/importer.py

- FIX: publisher name ending with ``.``  during folder creation would cause incorrect pathing
- FIX: auto-want upcoming error with annuals when used with annual integration

FIX: publisher name ending with decimal during folder creation, FIX: auto-want upcoming error with annuals

---

mylar/PostProcessor.py
mylar/notifiers.py

Followup to #1151
Improved Mattermost notifications to include some information about the issue being downloaded, all neatly confined with an attachment.

Refined Mattermost Notifications - now with cover!

---

Mylar.py
data/interfaces/carbon/css/style.css
data/interfaces/default/config.html
data/interfaces/default/css/style.css
data/interfaces/default/index.html
mylar/PostProcessor.py
mylar/__init__.py
mylar/carepackage.py
mylar/req_test.py
mylar/versioncheck.py
mylar/webserve.py

- IMP: warnings/info section added to configuration page 1st tab:
- Will indicate if current pip requirements have been met, and if unrar is able to be located (and thereby used). 
- If pip requirements not met, will indicate which module and why it wasn't met. 
- Any warnings will turn the section box red to draw attention.
- Messages section will relay messages from a .release_messages file in the data_dir location if present
- IMP: carepackage improvements:
- added release information where git branch, commit and version will now be written
- carepackage filename will now include the git commit and branch in the filename
- CLI option added to maintenance mode - ``maintenance -care`` or ``maintenance --carepackage``
- CLI option will run outside of the GUI so that it's possible to …

IMP: warnings/info section addition to config page, IMP: carepackage updates

---

mylar/cdh_mapping.py
mylar/sabnzbd.py

- changed ``comics`` hard-coded category check to use user-defined sabnzbd category
- proper/better handling of no category defined for sabnzbd when using CDH and the directory option.
- correct api call to sabnzbd for status/fullstatus endpoint dependent on sabnzbd client version
- fixed incorrect ``e`` reference on Exception during CDH mapping (which would traceback if triggered).

FIX:(#1181) CDH hard-coded category mapping

---

mylar/series_metadata.py

schema itself is not broken so no need to adjust. 
Users would just need to recreate series.json from this point forward (or let it auto-recreate for new / ongoing series)

FIX: cid mistakingly referenced druing series.json creation (reverted)

---

mylar/webserve.py

Currently, Story Arc entries which are marked as 'deleted' (indicates a manual deletion by the user) are still getting added to the watchlist despite being unwanted and invisible in the UI. This tweak to the SQL should filter out any 'deleted' entries.

FIX: Exclude deleted Arc items from AddMissingSeriesFromArc

---

data/interfaces/default/config.html
mylar/req_test.py

This would also affect schedulers not initialising at startup (and thereafter unable to run), if the requirements.txt file could not be located.
Also fixed the config page so that it will highlight the red border on failure to find / do pip comparisons.

FIX:(#1237)(#1243)(#1247) requirements.txt not found when data_dir is specified via CLI

---

mylar/__init__.py
mylar/sabnzbd.py
mylar/webserve.py

Previously, the SABnzbd version would only be checked when manually tested, or if the value for sab_version was set to None (typically a new installation). If SABnzbd was updated thereafter, mylar would not display the new version and instead would assume the initially tested version was being used. 
If the version was < 3.2.0, then this would restrict how much history mylar can retrieve from sabnzbd before assuming a download has failed. 
(This will allow for accommodation to future changes to the SABnzbd API if it should be required).
Also updated the config page so that it will auto-save the SABnzbd API key and SABnzbd version upon testing instead of waiting for the user to save things.

FIX:(#1230) Check SABnzbd version on startup sequence as opposed to manual / initial value only

---

data/interfaces/default/config.html
mylar/config.py
mylar/search_filer.py
mylar/versioncheck.py
mylar/webserve.py

Added Ignore Words (Search Restrictions) to the configuration page - Quality & Post-Processing.
Default values are set to:  ``.exe, .iso, pdf-xpost, pdf, ebook`` which obviously can be either removed or added to.
This currently only applies to searches atm - could possibly be included for post-processing, but this is the 1st step at least towards that.

IMP: Ignore Words - Search Restrictions added to Configuration page, FIX: branch history not displaying

---

data/interfaces/carbon/css/style.css
data/interfaces/default/comicdetails_update.html
data/interfaces/default/css/style.css
data/interfaces/default/upcoming.html
mylar/__init__.py
mylar/config.py
mylar/filechecker.py
mylar/helpers.py

- IMP: User-configurable search tier cutoff (config ini field ``search_tier_cutoff``, value in days). Will display cutoff in GUI as well.
- FIX:(#1254) Black & White issues not being properly recognised (works with ``001 Black``, ``001.Black``, ``001Black`` as well as with the ``#`` preceeding the issue number)
- FIX: CSS series page progress-bar fix (if no issues were present in series directory, no progress-bar would display to indicate have / total count)

IMP: User-configurable search tier cutoff, FIX:(#1254) Black & White issues, FIX: CSS series page progress bar

---

mylar/search.py

- FIX: History page not showing items snatched via DDL
- FIX: GUI notifications not firing off when snatches are via DDL (usually)

FIX: History page not showing DDL snatches, FIX: GUI notifs not firing on DDL snatches

---

mylar/torrent/clients/utorrent.py

seems to be an issue with python version > 3.10.x (reported with 3.10.6)
lower versions of python either ignore the invalid reference or ignore the error and still load the module from the lib folder.

FIX:(#1267) invalid library reference for utorrent module

---

mylar/PostProcessor.py
mylar/api.py
mylar/webserve.py

- IMP: (#1266) getWanted API endpoint will now return issues and annuals (and story_arcs when queried for)
- FIX: Manage page would not show full annual titles but just the series it was attached to (ie. ``Series`` as opposed to ``Series Annual``)

IMP: (#1266) getWanted endpoint, FIX: Manage page not showing full annual titles

---

mylar/config.py
mylar/sabnzbd.py
mylar/versioncheck.py

- IMP: set default docker paths for Comic Location (``/comics``) and SABnzbd Download directory (``/downloads``) (if not set)
- FIX: CDH category removal if not present when querying SABnzbd history
- FIX: remove eta variable from sabnzbd response as no longer supported (and wasn't really used)

IMP: Set generic default docker paths if not set, FIX: CDH query removals not needed

---

mylar/updater.py

Thus, nothing would get updated outside of the pull-list.

FIX: DBUpdater would traceback and kill scheduled job on CV entries with no comicid

---

mylar/filers.py

if $Imprint is used at the same directory level as other fields (ie. ``$Publisher - $Imprint/$Series...``), and the imprint doesn't exist - an extra space would remain which creates a directory structure that's not the intended one.

FIX:  imprint field being used within Folder Format string causing extra spaces

---

data/interfaces/default/comicdetails_update.html
mylar/helpers.py
mylar/importer.py
mylar/webserve.py

Issue table (series detail page) will display issue as per CV (ie. ``9 [5]``) - but will have a ``*`` beside it which will show a hovertip indicating that the issue also has legacy numbering.

FIX: adding series with legacy numbering (issue number in brackets)

---

data/interfaces/default/storyarc.html
mylar/PostProcessor.py
mylar/config.py
mylar/filers.py
mylar/helpers.py
mylar/webserve.py

This is not a retroactive option, if enabled it takes effect from the change point forward.
If you manually change the ``storyarc_location`` variable in the config.ini to a different location, you will have to:
- manually move the storyarc folder in it's entirety to the new location specified in the ini
- refresh each storyarc so that it can pull in the new location (otherwise it will report the wrong file locations to issues belonging to an arc)
** this last part I might try to automate a patch for, but atm - it has to be manual

IMP:(#1285) Change StoryArc base folder location via config.ini (storyarc_location)

---

mylar/__init__.py
mylar/filers.py
mylar/helpers.py

issue_exceptions in ini needs to have longest words starting with single letter matches first as opposed to last (or after, so ALPHA needs to come before A).
Tested with rename in GUI - should be the same for post-processing as it follows the same logistics with matching as above.

FIX:(#1277) invalid issue numbering with Alpha & Omega during rename

---

mylar/librarysync.py

My attempt to squash a very niche bug.  I had a bunch of comics with some very old scraper comments where there were numbers (in this case dates) later in the Notes field than the CVDBID / Issue ID.  The current parsing method did not account for this, so would not recognise the Issue ID correctly.  This change just uses a different regex approach to look for the first set of consecutive numbers following either "Issue ID" or "CVDB".  I've allowed it to ignore any characters between those prefixes and the ID in case there's some odd spacing/separators for some reason.
Example of Notes field that would fail on parsing the ID:
`Scraped metadata from ComicVine [CVDB196459] on 2011.05.20 08:41:41.`
The old method would strip this down to `196459 2011 05 20 08 41 41` and decide it wasn't a …

Tweaked Issue ID parsing on import to handle additional numbers in metadata Notes field

---

mylar/webserve.py

The "Search for Missing Search for Watchlist matches/Recheck Files" button throws an error when a file in the story-arc dir doesn't have an issue number (e.g. one-shots). The exception thrown:
File "/app/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.10/threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar3/mylar/webserve.py", line 1581, in addStoryArc
self.ArcWatchlist(storyarcid)
File "/app/mylar3/mylar/webserve.py", line 5166, in ArcWatchlist
temploc = tmpfc['issue_number'].replace('_', ' ')
'NoneType' object has no attribute 'replace'

FIX: rechecking Story-Arc directory fails on missing issue numbers

---

data/interfaces/default/config.html
data/interfaces/default/history.html
data/interfaces/default/importresults.html
data/interfaces/default/managecomics.html
data/interfaces/default/manageissues.html
data/js/script.js

This allows for the last variable in the doAjaxCall method in script.js to hold either ``'post'`` or ``'get'`` to indicate the type of ajax request to be made. 
If no method is provided (as most of the calls don't need to change), it will default to ``'get'`` (which is what it is currently).
ie. ``doAjaxCall('markissues',$(this),'table',true,'post')``.
jQuery > 1.9 has an alias for ``method``, which is ``type`` and is used by jQuery < 1.9  - so using ``type`` should be good enough to not break anything until we upgrade jQuery everywhere (and then we should switch to using ``method``).

FIX:(#1179) allow for POST method on pages where large amounts of data is being sent

---

mylar/__init__.py
mylar/config.py
mylar/cv.py

This will set the default behavior for the imprints aspect to take the CV naming convention over the imprints.json naming.
The imprint mappings that can be over-ridden are stored as a global variable in the __init__.py as a dictionary called ``IMPRINT_MAPPING``. If future mappings are needed, just add in the info and things should keep on trucking.
Given that some might want to use one or the other, a config.ini option ``imprint_mapping_type`` is now available. The choices are: ``CV`` - use CV imprint naming convention (this is the default)
``JSON`` - use the imprint.json naming convention over CV
This will only affect things going forward - might revisit it to go retroactively if alot got caught in the wrong naming schematic.

FIX:(#1321) imprints would take json naming convention over CV

---

mylar/webserve.py

basically if series title contained ``One-Shot``, the ``-`` in the title was being stripped and because the query to CV to find matches is somewhat strict it was failing to match against ``One-Shot``. 
Stupid, but fixed now.

FIX: During import, if title contained One-Shot - would not find the match on CV

---

mylar/search_filer.py

When it determines a search match, and it's a TPB/GN/One-Shot - it takes the series year as being the only acceptable year for a match. 
Which is fine if there's only one volume/issue on CV for that particular comicid. 
However, if multiple volumes are listed under one comicid and it falls under the TPB/GN - it would fail to match if the issue year was different than the series year.
This fix just allows it to match the issue year of the volume of the TPB correctly.

FIX: When determining match to download, TPB series spanning multiple years would fail to match

---

data/interfaces/default/comicdetails_update.html
mylar/helpers.py
mylar/webserve.py

Sets a default placeholder for some of the Edit Settings fields to ensure that they're not just blank.
Added blank space check for publisher imprint and alternate filename when saving the settings for a series. Just an attempt to make sure that if it's a space, it's not saved as that.
Also added in some code to throw some additional error logging when running external scripts.

FIX: When Alternate FileName field is blank, it writes a blank space

---

requirements.txt

Urllib3 recently had some breaking changes that breaks installation on docker (and possibly others).
This forces urllib3 to use the latest build under v2, since v2 has the breaking changes. 
This all might be caused by cfscrape which is used, but not in any capacity outside of mimicking requests (since the CF aspect is broken and the module is abandoned)

FIX:urllib3 breaking changes

---

mylar/PostProcessor.py
mylar/importer.py
mylar/librarysync.py
mylar/webserve.py

Should address / make usable (amongst others): #1336, #1232, #1231, #873
FIX: Import would fail when importing a filename with no issue number
FIX: Incomplete series would cause post-processing to fail if Latest Date and Publication Run were not generated
FIX: If annual gathering failed during generation, would break the add series queue
FIX: Import would fail if a series on the watchlist was being refreshed during, or if it hadn't completed for w/e reason

FIX: various import fixes (overdue school report)

---

mylar/librarysync.py

Newer comictagger versions don't add an [Issue ID XXXXXX] to the notes part of metadata. This adds a fallback if not found, to pull the issue ID instead from the webpage (if possible)

Fall back to webpage for newer ComicTagger versions

---

mylar/webserve.py

`os.rename` does not support cross-device renames and `shutil.move` should be used instead to support cross-device renames. 
Relevant documentation: https://docs.python.org/3/library/os.html#os.rename

FIX #1361: Use shutil.move to support cross-device renames

---

mylar/filechecker.py

Ignore placeholders / 0-byte files during file scans (post-processing / manual post-post-processing / cache scan / etc ) so that files used are actually files.

FIX: ignore 0-byte files/placeholders during filescans

---

mylar/getcomics.py

When hitting a `ConnectionError`, I observed the following in my log:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.10/threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar3/mylar/helpers.py", line 3241, in ddl_downloader
ddzstat = ddz.downloadit(item['id'], item['link'], item['mainlink'], item['resume'], item['issueid'], remote_filesize)
File "/app/mylar3/mylar/getcomics.py", line 923, in downloadit
logger.error('[ERROR] download has timed out due to inactivity...' % e)
TypeError: not all arguments converted during string formatting
```
This caused the DDL lock to never be released, …

getcomics: correct logging call

---

mylar/getcomics.py

This series of commits refactors the fetching of getcomics results pages into a separate method, and implements iterating through all of the search result pages.
I've tested this locally using Fantastic Four (2018) #3. It has a year mismatch between Mylar and GC, so the query which returns it is "Fantastic Four #3" which has enough results that it falls onto the second page. With trunk, the issue isn't found; with this branch, it is.
(I've broken the refactor down into logical commits, so reviewing commit-by-commit may make your life easier!)

getcomics: support fetching all search results using pagination

---

mylar/helpers.py

When downloading a pack, `ddzstat['path']` is the unpacked directory and `ddzstat['filename']` is set to `None`.  This commit avoids passing `None` to `os.path.join`, avoiding an exception.

helpers: handle absent filename in ddzstat

---

mylar/req_test.py

Configuration screen would indicate pip failure due to requests[socks] requirement change regardless of if it was installed or not.

FIX: Update configuration screen to allow for requests[socks] in requirements.txt

---

mylar/__init__.py

resulting in no queues being started

FIX: queues were not firing off due to a logging error that aborted the startup queue process

---

mylar/findcomicfeed.py
mylar/getcomics.py
mylar/rsscheck.py
mylar/search.py
mylar/search_filer.py

There are two main parts to this PR:
* it refactors `search_filer`s per-issue logic into a separate method, which allows us to reuse it for both the existing "get all matches" method, as well as a new "get the first match" method
* converts `getcomics`' `perform_search_queries` to generate each result, meaning we only fetch the next page when all of the results on the current page have been processed (as well as some associated refactoring to avoid exhausting the generator immediately)
Putting these together means that Mylar will now only fetch the next GC results page if it has not found a match on the current page: this should result in fewer results pages being fetched, reducing load on GC and improving search times.
I've split this down into a (hopefully) sensible sequence of commits. …

getcomics: stop searching when first matching issue is found

---

mylar/getcomics.py

I've run into issues on GC which have the short description HTML escaped
and so appearing as normal text: this means that it isn't queryable
using `.find`.  This commit detects that case and creates a new
`BeautifulSoup` object for the escaped HTML, and then searches it.
I've seen this fix searching for Batman (2016) issue 12, as it has such a
description.
(This is another PR with a dedent, so I recommend reviewing this with `?w=1` appended to the GitHub URL or `-w` passed to `git diff`.)

getcomics: handle literal-HTML descriptions which occasionally occur

---

mylar/config.py

These are not referenced anywhere, and the DDL definition overrides the Torrents definition.
Furthermore, as they default to false, they give a confusing impression of what Mylar will do by examining the config file, where you will see:
```
[DDL]
allow_packs = False
```
but Mylar will happily download packs regardless.  (Guess who was just confused by this while making my other pack-related change. :p)

config: remove unused ALLOW_PACKS configuration options

---

mylar/logger.py

Specifically, this adds *args, **kwargs to them. The stdlib logging functions are used when the language is detected as English.  Having them aligned avoids bugs like #1396, where a valid stdlib logging call caused a fatal error on a non-English installation.
(I have tested this by adding `LC_ALL=de_DE` to my development instance's environment and reverting 457fceb0 (the fix for #1396): without this patch, the reported error occurs; with this patch, Mylar starts up just fine.)
Fixes: #1398

logger: align custom non-English logger functions with stdlib

---

data/interfaces/default/manage.html
mylar/webserve.py

This doesn't enable performing any actions on the queues or workers, but does make it easier to understand what the current status is (and perhaps gives us a place to put actions in future).
I've tested this by locally modifying `helpers.search_queue` to raise an Exception after 10s (so I didn't have to figure out how to trigger a legit error). The screenshot above is taken after searching for a single issue after the 10s has elapsed, hence the queue length.

manage: add Queues section to Activity/Jobs tab

---

mylar/search.py

Specifically, we would see a traceback if there were issues for a search in the RSS feed database: this fixes that codepath to pass the correct values to `checker()`.
(This must be the change I should have made instead of that other change we ended up undoing.)

search: fix call of sfs.checker when using DDL RSS search

---

mylar/getcomics.py

I saw an exception like this in my log, and the DDL queue stopped being processed:
```
Aug 30 18:46:41 X mylar3[3028235]: Traceback (most recent call last):
Aug 30 18:46:41 X mylar3[3028235]:   File "/app/mylar3/mylar/logger.py", line 337, in new_run
Aug 30 18:46:41 X mylar3[3028235]:     old_run(*args, **kwargs)
Aug 30 18:46:41 X mylar3[3028235]:   File "/usr/lib/python3.11/threading.py", line 975, in run
Aug 30 18:46:41 X mylar3[3028235]:     self._target(*self._args, **self._kwargs)
Aug 30 18:46:41 X mylar3[3028235]:   File "/app/mylar3/mylar/helpers.py", line 3244, in ddl_downloader
Aug 30 18:46:41 X mylar3[3028235]:     if ddzstat['success'] is True:
Aug 30 18:46:41 X mylar3[3028235]:        ~~~~~~~^^^^^^^^^^^
Aug 30 18:46:41 X mylar3[3028235]: TypeError: 'NoneType' object is not …
```

getcomics: fix missing lock release/return value in downloadit

---

mylar/getcomics.py

So, if users had problems with CF-related errors (small tank, read timeouts, etc), or if they were using FS and it still wouldn't work due to cookie failure - this should fix the issues based on some quick tests we did in discord today.
This won't bypass IP bans by CF if that's actually occuring.

FIX: DDL failing to search/download due to CF/FS problems

---

data/interfaces/default/manage.html
mylar/helpers.py
mylar/webserve.py

Also includes some refactoring to the queue view in Manage, as it's the same data being presented.
This allows people with a Prometheus instance to scrape the current queue status. Here's an example of the queue sizes when downloading 9 issues (from 2 series, hence the staggered initial increase) from GC:
It also exposes "alive" and "started" metrics which should enable people to add alerting for queues dying, if desired.

Expose current queue status at /prometheus_metrics for Prometheus monitoring

---

mylar/weeklypull.py

Emit a WARNING log message instead of a traceback.

weeklypull: handle invalid annuallink values gracefully

---

mylar/config.py

I've had it happen on more then one occassion when spinning up an instance to test something, that the field for the ComicVine API key on the Web interface was still sporting the initial value of 'None'. Which I only noticed when the search results still wouldn't pop in with the key set. 
This PR works around that happening by just seeing if the string starts with 'None' and ignoring that.

Working around accidentally invalid API key (starting with None)

---

mylar/filechecker.py

the pwd and grp python modules are not available on windows platforms - so only load the modules if it's non-windows.

FIX: pwd/grp modules not available on windows

---

mylar/__init__.py

- pack column added to allow for pack names being used on the manage DDL page as opposed to the series and issue number that was searched for.
- future segway into being able to monitor individual parts of a pack during download / post-processing in an attempt to stop repeated downloads of packs occuring

FIX: unable to load Manage DDL page due to invalid reference

---

mylar/importer.py

previous PR :  if a series was paused and forcibly marking new issues as Skipped instead of Wanted
problem: the test was too open and not based on the actual status of the series
solution: dis.

FIX: new issues set to Skipped even when series is not paused

---

mylar/search.py
mylar/updater.py

- FIX: when searching for issues published in late 2023, wouldn't match to 2024 filenames due to invalid date comparison
- FIX: mark all issues as wanted config option would mark every issue of a series as Wanted after each recheck/refresh that was not in a Downloaded status, regardless of previous state (ie. manually marking an issue as Skipped)

FIX: 2024 / 2023 search problem matching, FIX: Mark all issues as Wanted being too literal

---

mylar/filechecker.py
mylar/webserve.py

FIX: (#1461) MAC OS metadata files would be scanned in mistakingly during series page loads / rechecks

---

mylar/sabnzbd.py

``logger.warning`` doesn't exist - should be ``logger.warn`` for non-english locales (stupid but meh).

FIX:(#1469) incorrect logger reference causing traceback on SAB snatches that are completed quickly

---

mylar/req_test.py
requirements.txt

- increase versions for cheroot (``>8.2.1``) and pillow (``>10.1`` due to python3.12 not working on less than this verison).
- fix pillow check so it's case-insensitive (went from ``Pillow`` to ``pillow``)

FIX:(#1471) Update cheroot and Pillow to use latest if available - fixes pillow error being listed in config page

---

data/interfaces/default/queue_management.html
mylar/getcomics.py
mylar/helpers.py
mylar/search.py
mylar/webserve.py

- DDL would loop thru available links in an endless loop if first link was not available
- scheduled searches will have status checked prior to actually searching (cannot be in a Downloaded or Snatched status) unless it was initiated manually (ie. magnifying glass search)
- Added Remove option to DDL table options so items that are stuck in a Start/Incomplete status can be removed

FIX: DDL attempting items in a forever loop, FIX: scheduled searches would re-attempt previous downloads

---

mylar/cv.py
mylar/getimage.py
mylar/helpers.py
mylar/search.py
mylar/updater.py
mylar/webserve.py

- If cover image on series detail page is corrupted/corrupt - would error. It will now attempt to download a clean copy of the main image, and if that fails try an alternate image size (it may take a few seconds to display in page, will add a popup indicating)
-  dbupdater would error when attempting to merge previous_failed_id info into a non-existent dictionary
- Wanted page may not display if IssueNumber field is blank or some other field is empty. Will attempt to default to ComicName.
- On successful DDL downloads, if the link used worked :
- If it was the first link used, would cause a traceback when clearing the queue of the id
- If it was a retry/requeue, would error on attempting to preload a variable that's not really needed (one-shot) / site name
- DDL ReQueue / Restart would …

various fixes (see notes)

---

mylar/config.py
mylar/getcomics.py
mylar/helpers.py

- FIX: endless DDL looping would occur when all links were behind a paywall site and link exhaustion could not occur
- FIX: html_cache in cache_dir for GC html files so won't redownload html file until item is successfully downloaded.
- FIX: html_cache location added to cleanup_cache section
- IMP: default ``usenet_retention`` set to **3500** days.
- IMP: default ``enforce_permissions`` set to **False**
- IMP: default metatagging option ``cmtag_start_year_as_volume`` set to **True**

FIX: endless DDL looping when paywall site encountered, and some other fixes

---

mylar/cv.py
mylar/search_filer.py
mylar/updater.py

- FIX: Booktype will default to Print instead of None when adding a series
- FIX: Error when searching for items being returned with no issue numbers and doing comparison checks
- FIX: One-Shots booktype not able to scan in issues with no issue number (independent annuals)

FIX: booktype will default to Print instead of None, FIX: error when searching for items being returned no issue numbers

---

mylar/config.py

Just removed the check - if they're running sabnzbd < 0.8.0 there is probably more to worry about than mylar not starting up...

FIX:(#1502) sabnzbd version detection problem on startup re: versioning format

---

mylar/getcomics.py

Only an issue during failure of previous links resulting in one usable link, or if there was only one available link available.

FIX: would fail to set selection when previous failures resulted in main link being used

---

data/interfaces/carbon/css/style.css
data/interfaces/default/comicdetails_update.html
data/interfaces/default/css/style.css
data/interfaces/default/index-alphaindex.html
data/interfaces/default/index.html
mylar/__init__.py
mylar/cv.py
mylar/helpers.py
mylar/importer.py
mylar/webserve.py

Will check existing information in db with what CV is telling it is supposed to be. It will now do 4 comparison checks - if > 50% of the checks fail, it will assume it's been changed and indicate as such. It will then:
- automatically pause the series
- flag it as ``cv_removed`` color coded on the main watchlist page
- when loading the series detail page for the given series, it will prompt with an explanation and 2 choices:
- delete: delete the series from the watchlist (also an option to delete the series from the disk)
- keep: will retain the series as is with no further information being retrieved from CV
*Note: this also adds a color-coded legend to the bottom of the main watchlist/index page, along with color-coded rows now for  status of : ``cv_removed``, ``loading``, ``paused``, …

IMP: Detect and handle CV reusing existing ComicIDs

---

mylar/series_metadata.py

Simple fix here, have tested it locally fixes this error message:
```29-Feb-2024 14:51:09 - ERROR   :: mylar.excepthook.315 : mass-refresh : Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/local/lib/python3.9/threading.py", line 917, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar/mylar/updater.py", line 53, in addvialist
dbUpdate([item['comicid']], calledfrom='refresh')
File "/app/mylar/mylar/updater.py", line 233, in dbUpdate
chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, calledfrom='dbupdate', annload=annload, csyear=csyear, fixed_type=fixed_type)
File "/app/mylar/mylar/importer.py", line 469, in addComictoDB
updateddata = updateissuedata(comicid, …
```

fix casing when invoking updater.dbUpdate

---

data/interfaces/default/base.html
data/interfaces/default/comicdetails_update.html
data/interfaces/default/config.html
data/interfaces/default/index.html
data/interfaces/default/searchresults.html
lib/comictaggerlib/comicvinetalker.py
lib/comictaggerlib/main.py
lib/comictaggerlib/settings.py
mylar/PostProcessor.py
mylar/config.py
mylar/downloaders/mediafire.py
mylar/getcomics.py
mylar/importer.py
mylar/notifiers.py
mylar/rsscheck.py
mylar/search.py
mylar/search_filer.py
mylar/webserve.py
mylar/weeklypull.py

Hate doing this much in one PR, but if it doesn't go like this, it'll end up sitting for god knows how long (or I'll forget entirely):
IMP: Update current default user_agent string to a more current string
IMP: CT will now use user_agent string defined by Mylar as opposed to a random generic one on each request (if not updated, will force-update it accordingly)
IMP: Removed individual provider entries for nzbsu and dognzb from GUI, now treated as newznabs. If enabled, will be converted to newznab entry provided doesn't already exist as a newznab.
IMP: If CV indicates series year does not exist (ie. 2099) instead of using 2099, will use year of first issue or if not invalid, current year 
IMP: When refreshing/adding a series that has a directory created with the incorrect year (2099), …

FIXES...FIXES...FIXES..(and a few improvements)

---

data/interfaces/default/comicdetails_update.html
mylar/filers.py

2 small patches:
- removal of ``()`` (empty paranthesis) leftover during folder creation when removing fields that do not exist
- collected editions will display what items they collect under Edition, if the items are not in the watchlist the link will redirect to the specific series on CV (as opposed to being in the watchlist, where it already will redirect to the watchlist item).

Removal of () in folder structure, link to CV for items within collected editions

---

mylar/__init__.py
mylar/config.py

- ``cleanup_cache`` is enabled to True by default now.
- ``ddl_location`` would not be honored if set in config.ini (would always default to cache location)
- ``cleanup_strays`` added to allow for removal of cbr/cbz/zip files. By default if enabled this will clear out just the _cache_dir_ location of said files. However if _ddl_location_ is set it will also cleanup that specified location as well.

FIX: ddl_location would not be honored, FIX: optional cbr/cbz cache removal added

---

mylar/config.py

would result in a traceback after finding a ddl match....

FIX: html_cache would not be found when using ddl after saving settings without a restart

---

data/interfaces/default/config.html
mylar/config.py

PR to address #1551.  
Removing the option entirely would leave the UI looking a bit odd with both an "Enable MetaTagging" checkbox, then a single checkbox for the remaining type (ComicRack).  I did consider removing the former, consolidating to a single toggle, and making tagging implicit on either CR or CBL tagging being set.  Unfortunately, this would cause problems for upgrades for anyone who doesn't currently have the ENABLE_META flag set, as the default value for the other two flags (CT_TAG_CR, CT_TAG_CBL) is True, so they would suddenly start tagging.  
In the end I settled on this simpler approach:
- Make the default value of CT_TAG_CBL False.  This should hopefully avoid new users enabling it just because it's there.
- Disable the ComicBookLover checkbox when it is unchecked. …

De-emphasising CBL tagging

---

mylar/filechecker.py
mylar/webserve.py

Noticed in passing while doing other changes, isolating them to a standalone PR.  One typo in "Exception", one reference to a variable that isn't declared (and should be "cid" within the loop).

Fix: Misc typos

---

data/interfaces/default/config.html
mylar/config.py
mylar/nzbget.py
mylar/webserve.py

- nzbget URL subpath option added to GUI
- None option added to Usenet radio selection - will default to None for new installations
- if sab/nzbget are enabled and their host values are empty (or blackhole is enabled and directory value is empty) will save it as if the None option was selected (on save only)

IMP: nzbget subpath option added to GUI, IMP: None option added to Usent radio selection

---

mylar/downloaders/pixeldrain.py
mylar/helpers.py

closes #1569, #1568,  #1556, #1550 
also fixes pixeldrain related errors when file not found / captcha required.

FIX: comicinfo is None / links_exhausted error

---

mylar/PostProcessor.py

A check for an issue number being in range of those in the volume was failing as it assumed the biggest issue number (named LatestIssueInt but should really be HighestIssueInt given how it is used) would be found sorted on release date.  Ironically, this was working for series with incomplete metadata, but not for those with release dates in the right place for the problem issues.  Observed in DC One Million releases which were all released mid-volume, was causing those issues to not process for some series depending on metadata quality.
Closes https://github.com/mylar3/mylar3/issues/1585

Fix: Post processor check for non-ordered issue # by release date

---

mylar/PostProcessor.py
mylar/importer.py

See issue https://github.com/mylar3/mylar3/issues/1623
- A general fix for correctly identifying the highest issue number when the issue numbers are not >= 0
- A specific fix for post processing on one-shot types to consider a possibility of a negatively issue numbered one-shot

Fix: Negative numbered volume fixes

---

mylar/webserve.py

Due to changes in how the weekly dates are calculated, the upcoming section was using the old method that wouldn't show dates until the day of release. 
It will now show the releases starting on Sunday (as expected) and as it was previous to the date changes.

FIX: This Week's Upcoming section would not display upcoming issues for the week

---

mylar/config.py

Changed the default search time from 360 minutes to 1440 minutes. 
I think this better aligns with how comics are being released these days and also feels like a better default option for new users who are adding a lot of issues to their watchlist. We have had a influx of people coming to support channels who are just starting out using mylar and adding 500+ issues off the bat.

Update config.py for better default search interval

---

mylar/notifiers.py

When I first poked around to write this, the notifier did not account for two things:
- imageFile being None (which would cause the notifier to barf)
- the base64-encoded string hitting a server-side max_body_size, resulting in a 400 - Bad Request and a log entry of "Premature EoF" on the side of the Mattermost instance
I decided to remove the image from the payload for these two reasons.
Alos this fixes the Test function (which didn't barf, but plain refused to work).
Now with 100% more correct branch base... Keep forgetting branching off python3-dev

Fixing shortcomings of the mattermost notifications

---

mylar/PostProcessor.py
mylar/helpers.py

Implemented file type checks and CRC checks for downloads from DDL, Usenet, Folder_Cache, and Manual Post-Processing.  Where possible the check is done straight after the download to enable "failed" marking, but for packs and manual that's not really possible so it happens in post processing.  That can cause a second pass of it, but it's harmless so wasn't worth branching for.
Currently, it will reject anything that isn't a PDF, zip, rar, or 7zip.  Can easily change that default behaviour if preferred.  It may help flag up failures with cloudflare as it'll read them as text files (no magic numbers) and reject them on quality grounds.
CRC checking is done for zip and rar using existing libraries.  7z and PDF are just passed if detected with valid header bytes.
Managed to find both bad rars …

CRC checks on downloads and manual post-processing

---

mylar/search.py

I've now seen someone question this warning at least twice, so might as well prevent it happening again :)
Adds manual searches into the default 30s case.
Fixes #1649

Tweaked search delay check to no longer give misleading warning on manually triggered searches

---

data/interfaces/carbon/css/style.css
data/interfaces/default/base.html
data/interfaces/default/cblimport.html
data/interfaces/default/css/style.css
data/interfaces/default/manage.html
data/interfaces/default/storyarc.html
mylar/__init__.py
mylar/config.py
mylar/importer.py
mylar/webserve.py

A new screen for importing CBL reading lists.  Depends on lists that are well populated with CV ID data (i.e. it doesn't attempt any lookup by names).
- Accessible via either Manage->Advanced->CBL Import or StoryArcs->CBL Import
- Uses the MASS-ADD queue to add series and then toggle wanted status for issues once it is dry
- Does not actively prevent someone trying to add more than the CV limit, but does offer some warnings at >100 or >200 volumes being added in one list
- Options to suppress autowant-all when adding volumes if it is enabled in settings (default is to do so)
Couple of random little typo fixes buried in there as well.

CBL Reading List Import Screen

---

data/interfaces/default/config.html

Shows red warning text when a user is setting the folder monitoring to look at either the comic location or the SAB download location (or parents of).  Does not prevent them saving the changes, but should hopefully discourage mishaps.

Warning text for bad choices in folder monitoring

---

data/interfaces/default/upcoming.html
mylar/webserve.py

I had missed a very obvious case of selecting a single issue on the wanted page for checking causing the issueIds to not be passed as a list.  Clearly I've been using the magnifying glass too much ...

Fix exception on single wanted issue submit, revert button text on refresh

---

data/interfaces/default/config.html
mylar/PostProcessor.py
mylar/config.py
mylar/downloaders/__init__.py
mylar/downloaders/airdcpp.py
mylar/rsscheck.py
mylar/search.py
mylar/search_filer.py
mylar/webserve.py

Initial implementation of using AirDC++ Web to search and download. Also monitors release announcement hubs as if they were RSS feeds. Likely there are some things I am not doing correctly as I am not that familiar with the Mylar codebase, but I have tested it and verified it can search, download and post process, and that rss force + schedule work. I put it in Search Providers near DDL - it is both search and download so wasn't sure. 
My test environment was a dockerised verlihub and a pair of airdc++ containers. I used one container to be the search endpoint and the other to share the comics. Both connected to the test hub. I then created an API user in AirDC++ under Settings, System, Add User and put those credentials into Mylar. 
Features:
* Hub filter - important in case you don't …

AirDC++ for Search & Download (rebase)

---

mylar/config.py

Try adding a provider to a new mylar install.  Save.  Try renaming the provider.  Error.
When it tries to update the active entries from PROVIDER_ORDER, it is checking new names against old names so misses the existing entry and fails the UNIQUE constraints on id and provider name when upserting.  Simplest solution is to only upsert against the id.

FIX: Fixed DB error on changing newznab provider names

---

mylar/helpers.py
mylar/webserve.py

When annual integration is enabled, a story arc issue is an annual, it will sometimes match issues and sometimes will not. I debugged this, and found that this one line was not returning an issue in these cases. Looking at the DB, it was failing to match up the id between the annuals and storyarcs tables correctly. It was looking at the annuals table's comicid (which is the main comic series id) instead of the releasecomicid (which is the annual series id). Changing this to releasecomicid causes it to properly match.
After this change, I stood up the server locally with my entire DB, and tried searching for missing on several story arcs, some with annuals and some without. I also tried refreshing several story arcs. Saw no errors or issues, and the bug was fixed.

FIX: Story Arcs with annual issues didn't work when annual integration is on
